"""Loads car data from individual JSON files in data/cars/.

Each file is a flat dict containing a "name" key (the display name) plus all
the car's data fields. Files are numbered (NN-slug.json) so sorting filenames
preserves the curated order.
"""

import glob
import json
import os

DATA_DIR = os.path.join(os.path.dirname(__file__), "data")
CARS_DIR = os.path.join(DATA_DIR, "cars")
CATALOG_FILE = os.path.join(DATA_DIR, "catalog.json")
BREAKDOWNS_DIR = os.path.join(DATA_DIR, "breakdowns")


def load_cars():
    """Return an ordered dict of {display_name: car_data} from data/cars/*.json."""
    cars = {}
    for path in sorted(glob.glob(os.path.join(CARS_DIR, "*.json"))):
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        name = data.pop("name")
        cars[name] = data
    return cars


def load_catalog():
    """Return the lightweight enthusiast catalog (list of dicts), or [] if absent.

    These are NOT full curated cars - just make/model/year/generation/body/note
    that the data engine enriches on demand. Generated by scripts/build_catalog.py.
    """
    if not os.path.exists(CATALOG_FILE):
        return []
    with open(CATALOG_FILE, encoding="utf-8") as f:
        return json.load(f)


def load_breakdown(slug):
    """Return the Teardown/breakdown descriptor for a model slug, or None if absent.

    One JSON per 3D model in data/breakdowns/<slug>.json: an ordered list of the
    car's essential parts, each with the GLB materials that compose it (for the
    exploded 3D view), a fitted-space anchor, and info grounded on the curated car.
    `slug` is caller-supplied, so restrict it to a safe filename before touching disk.
    """
    if not slug or not all(c.isalnum() or c == "-" for c in slug):
        return None
    path = os.path.join(BREAKDOWNS_DIR, f"{slug}.json")
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8") as f:
        return json.load(f)
