print("Welcome to Garage AI")

cars = {
    "Honda Civic Si": {
        "engine": "1.5L turbo I4",
        "horsepower": 200,
        "torque": "192 lb-ft",
        "drivetrain": "FWD",
        "transmission": "6-speed manual",
        "0_to_60": "6.7 sec",
        "fuel_economy": "27 city / 37 hwy mpg",
        "curb_weight": "3,012 lbs",
        "reliability": "8/10 — bulletproof Honda drivetrain; watch 10th-gen oil dilution",
        "cost_to_own": "Insurance: Moderate-High (turbo compact, young-driver target) · Maintenance ~$400/yr",
        "popular_mods": [
            "Hondata FlashPro ECU tune (+50-70 whp — the single biggest gain)",
            "Cold air intake + upgraded front-mount intercooler",
            "Catback exhaust + downpipe",
            "Lowering springs or coilovers + rear sway bar",
            "Summer performance tires — the chassis can use more grip than stock",
        ],
        "oil_type": "0W-20 full synthetic",
        "oil_interval": "Every 5,000-7,500 miles",
        "generations": {
            "5th Gen EG (1992–1995)": "125hp D16Z6 VTEC — first Civic Si with VTEC, double-wishbone suspension all around.",
            "6th Gen EK (1996–2000)": "160hp B16A2 — cult classic coupe (EM1). Last gen with front double-wishbone. Highly sought after.",
            "7th Gen EP/EM (2002–2005)": "160hp K20A3 — EP3 hatchback in Europe, EM2 coupe in North America. Dropped double-wishbone up front.",
            "8th Gen FG (2006–2011)": "197hp K20Z3 — high-revving VTEC, 6-speed manual, limited-slip diff. First Si sedan debuted in 2007.",
            "9th Gen FB (2012–2015)": "201hp K24Z7 — largest engine in Si history, 2.4L naturally aspirated, limited-slip diff, 31mpg highway.",
            "10th Gen FC/FK (2017–2021)": "205hp 1.5L turbo (L15B7) — returned to turbo power, broader torque band, known for oil dilution in cold climates.",
            "11th Gen FE1 (2022–present)": "200hp 1.5L turbo — slight power drop but torque peaks earlier (below 2,000 rpm). Better daily driveability.",
        },
        "common_issues": [
            "Oil dilution (fuel mixing into oil in cold climates) — affects 10th gen most",
            "AC compressor failure",
            "Infotainment freezing",
        ],
        "maintenance_tips": [
            "Check oil level frequently on 10th gen due to known dilution issue",
            "Use Honda-approved 0W-20 synthetic",
            "Inspect brake pads — sport driving wears them faster",
        ],
    },
    "Subaru WRX": {
        "engine": "2.4L turbo H4 (FA24F)",
        "horsepower": 271,
        "torque": "258 lb-ft",
        "drivetrain": "AWD",
        "transmission": "6-speed manual / CVT",
        "0_to_60": "5.5 sec",
        "fuel_economy": "19 city / 26 hwy mpg",
        "curb_weight": "3,320 lbs",
        "reliability": "7/10 — rugged boxer/AWD; CVT and older EJ head gaskets are weak points",
        "cost_to_own": "Insurance: High (rally reputation, high theft/claim rates) · Maintenance ~$680/yr",
        "popular_mods": [
            "Cobb Accessport ECU tune (E85 flex-fuel popular)",
            "Catless/high-flow downpipe, intake, top-mount intercooler",
            "Catback exhaust",
            "Coilovers or lowering springs + front/rear sway bars",
            "Note: FA24 is knock-sensitive — use a conservative, well-proven tune",
        ],
        "oil_type": "5W-30 full synthetic",
        "oil_interval": "Every 6,000 miles",
        "generations": {
            "1st Gen GC/GF (1992–2000)": "JDM only initially. 237hp EJ20T boxer turbo. Became a rally legend with Prodrive WRC campaigns.",
            "2nd Gen GD/GG (2002–2007)": "First gen sold in the US. 227hp EJ205. Three face styles: bugeye (2002–03), blobeye (2004–05), hawkeye (2006–07).",
            "3rd Gen GE/GH (2008–2014)": "265hp EJ255. Wider body option. Last generation to use the iconic EJ engine family.",
            "4th Gen VA (2015–2021)": "268hp FA20F — switched to direct-injection FA-series engine. First WRX as its own standalone model (not Impreza WRX).",
            "5th Gen VB (2022–present)": "271hp FA24F — grew to 2.4L. CVT added alongside manual. Dropped hatchback body, polarizing choice among fans.",
        },
        "common_issues": [
            "Head gasket failure (older EJ engines — less common on FA24)",
            "CVT reliability concerns at high mileage",
            "Turbo heatsoaking on track use",
        ],
        "maintenance_tips": [
            "Change oil every 6k miles — turbos punish extended intervals",
            "Let engine warm up before pushing hard",
            "Inspect intercooler hoses for cracks at 60k+",
        ],
    },
    "Audi S3": {
        "engine": "2.0L turbo I4 (EA888)",
        "horsepower": 306,
        "torque": "295 lb-ft",
        "drivetrain": "AWD (Quattro)",
        "transmission": "7-speed dual-clutch (S tronic)",
        "0_to_60": "4.4 sec",
        "fuel_economy": "23 city / 32 hwy mpg",
        "curb_weight": "3,527 lbs",
        "reliability": "6/10 — fast and refined, but carbon buildup and German upkeep costs add up",
        "cost_to_own": "Insurance: High (luxury performance, costly parts) · Maintenance ~$950/yr (Audi avg ~$987)",
        "popular_mods": [
            "APR or Unitronic Stage 1-2 ECU tune (330-370+ hp)",
            "Intake, upgraded intercooler, downpipe",
            "DSG/TCU transmission tune for faster, firmer shifts",
            "IS38 turbo upgrade for big-power builds",
            "Coilovers + sway bars",
        ],
        "oil_type": "5W-40 full synthetic (VW 502.00 spec)",
        "oil_interval": "Every 10,000 miles (Audi LongLife) — recommend 5,000 for longevity",
        "generations": {
            "1st Gen 8L (1999–2003)": "210–225hp 1.8T inline-4. Facelift in 2002. The S3 that started it all — compact, Quattro AWD, surprisingly quick.",
            "2nd Gen 8P (2006–2012)": "261hp 2.0T FSI. Available in 3-door and 5-door. 0–62 in 5.7 sec. Electronically limited to 155mph.",
            "3rd Gen 8V (2013–2020)": "300hp at launch, bumped to 310hp in 2016 facelift. Sharper styling. Available as sedan (2014+) and convertible.",
            "4th Gen 8Y (2020–present)": "306hp 2.0T. Aggressive new look with widened fenders ('Quattro Blisters'). Shift-by-wire shifter replaces traditional gear selector.",
        },
        "common_issues": [
            "Carbon buildup on intake valves (direct injection) — all generations",
            "DSG shudder at low speeds when cold",
            "Water pump and thermostat failure (60-90k miles)",
        ],
        "maintenance_tips": [
            "Walnut blast intake valves every 40-60k miles",
            "Use only VW 502.00 approved oil — non-spec oil voids warranty",
            "Replace water pump and thermostat proactively at 80k",
        ],
    },
    "Ford Mustang GT": {
        "engine": "5.0L V8 (Coyote)",
        "horsepower": 460,
        "torque": "420 lb-ft",
        "drivetrain": "RWD",
        "transmission": "6-speed manual / 10-speed auto",
        "0_to_60": "4.3 sec",
        "fuel_economy": "15 city / 24 hwy mpg",
        "curb_weight": "3,705 lbs",
        "reliability": "7/10 — robust Coyote V8; hard launches and track use stress the drivetrain",
        "cost_to_own": "Insurance: Very High (V8 muscle, ~$2,655/yr avg) · Maintenance ~$710/yr",
        "popular_mods": [
            "Supercharger (Roush/Whipple/Procharger) — the big power move, 700+ hp",
            "Cold air intake + ECU tune",
            "Long-tube headers + catback exhaust",
            "Lowering springs/coilovers + subframe bushings",
            "Sticky tires to tame wheel hop on launches",
        ],
        "oil_type": "5W-50 full synthetic",
        "oil_interval": "Every 7,500 miles (normal) / 5,000 miles (track use)",
        "generations": {
            "4th Gen SN95 (1994–2004)": "215hp 5.0L pushrod V8 at launch, swapped to 4.6L modular OHC V8 in 1996 (260hp). 'New Edge' facelift in 1999.",
            "5th Gen S197 (2005–2014)": "300hp 4.6L V8 (2005–2010). Major upgrade in 2011 with 5.0L Coyote DOHC producing 412hp. First Mustang on its own platform.",
            "6th Gen S550 (2015–2023)": "435hp at launch, bumped to 460hp in 2018. First Mustang with independent rear suspension. Available worldwide for the first time.",
            "7th Gen S650 (2024–present)": "480–486hp Coyote V8 (with active exhaust). New dual-throttle intake. Most powerful stock GT ever built.",
        },
        "common_issues": [
            "IRS half-shaft failure under hard launches (S550+)",
            "Transmission fluid overheating on track (10-speed auto)",
            "Wheel hop with manual on stock tires",
        ],
        "maintenance_tips": [
            "Upgrade diff and transmission fluid to racing spec if tracking",
            "Check rear axle half-shafts if launching hard regularly",
            "Coolant overflow tank cracks over time — inspect at 50k+",
        ],
    },
    "Toyota GR86": {
        "engine": "2.4L flat-4 (FA24)",
        "horsepower": 228,
        "torque": "184 lb-ft",
        "drivetrain": "RWD",
        "transmission": "6-speed manual / 6-speed auto",
        "0_to_60": "6.1 sec",
        "fuel_economy": "20 city / 27 hwy mpg (manual)",
        "curb_weight": "2,811 lbs",
        "reliability": "8/10 — simple, light, naturally aspirated; few chronic issues",
        "cost_to_own": "Insurance: Moderate-High (sports coupe, but cheap & low-power) · Maintenance ~$755/yr",
        "popular_mods": [
            "Forced induction (HKS turbo / supercharger kits, 300+ hp) — main power path",
            "Cold air intake, catback exhaust, Tomei header",
            "ECU tune (modest NA gains — power isn't this car's strength)",
            "Coilovers, sway bars, chassis bracing, sticky tires — transforms the car",
            "Big brake kit for track use",
        ],
        "oil_type": "0W-20 full synthetic",
        "oil_interval": "Every 6,000 miles",
        "generations": {
            "1st Gen ZN6 — Scion FR-S (2012–2016)": "200hp 2.0L FA20 flat-4. Co-developed with Subaru (sold as BRZ). Scion branding in the US until the brand was killed in 2016.",
            "1st Gen ZN6 — Toyota 86 (2017–2020)": "205hp after revised gear ratios and minor tune update. Rebranded Toyota 86 after Scion was discontinued.",
            "2nd Gen ZN8 — Toyota GR86 (2022–present)": "228hp 2.4L FA24 — 18% more power, 11% more torque. Subaru Global Platform adds 50% more torsional rigidity. Nearly a full second quicker to 60.",
        },
        "common_issues": [
            "Low torque at low RPM — power lives above 4,500 rpm (1st gen especially)",
            "Clutch wear if slipping on spirited launches",
            "Infotainment lag (minor)",
        ],
        "maintenance_tips": [
            "Let revs climb before shifting — engine rewards high RPM",
            "Brake fluid degrades quickly on track — flush every season",
            "Tires wear fast under spirited driving — check pressure often",
        ],
    },
    "Infiniti Q50 3.7": {
        "engine": "3.7L V6 (VQ37VHR)",
        "horsepower": 328,
        "torque": "269 lb-ft",
        "drivetrain": "RWD / AWD",
        "transmission": "7-speed automatic",
        "0_to_60": "5.3 sec (RWD)",
        "fuel_economy": "20 city / 29 hwy mpg (RWD)",
        "curb_weight": "3,574 lbs",
        "reliability": "7/10 — durable VQ V6; watch oil consumption and warping brake rotors",
        "cost_to_own": "Insurance: Moderate (luxury sedan) · Maintenance ~$650/yr",
        "popular_mods": [
            "Uprev or Ecutek ECU tune",
            "Cold air intake, headers, catback exhaust (modest NA gains)",
            "Plenum spacer / underdrive pulley",
            "Coilovers + sway bars",
            "Note: naturally aspirated — gains are modest vs the turbo VR30 cars",
        ],
        "oil_type": "5W-30 full synthetic (Nissan Ester oil recommended)",
        "oil_interval": "Every 5,000-6,000 miles",
        "generations": {
            "2014 (Launch)": "Debuted at 2013 NAIAS. Replaced the G37. Introduced Direct Adaptive Steering (steer-by-wire). 3.7L VQ37VHR and Hybrid (354hp) available.",
            "2015": "Final year of the 3.7L engine. Minor refinements. Last chance to get the naturally aspirated V6 in the Q50.",
        },
        "common_issues": [
            "Valve train noise — often quieted with Nissan ester oil",
            "Rear timing cover gasket leak (oil pressure stresses paper gasket)",
            "Oil consumption from worn valve seals or piston rings at high mileage",
        ],
        "maintenance_tips": [
            "Use Nissan genuine ester oil to reduce valve train noise",
            "Inspect rear timing cover for oil seepage at 60k+ miles",
            "Check oil level every fill-up — engine can consume oil silently",
        ],
    },
    "Infiniti Q50 3.0t": {
        "engine": "3.0L twin-turbo V6 (VR30DDTT)",
        "horsepower": 300,
        "torque": "295 lb-ft",
        "drivetrain": "RWD / AWD",
        "transmission": "7-speed automatic",
        "0_to_60": "5.1 sec",
        "fuel_economy": "20 city / 29 hwy mpg (RWD)",
        "curb_weight": "3,820 lbs",
        "reliability": "6/10 — strong engine, but turbo complexity and wastegate rattle at mileage",
        "cost_to_own": "Insurance: Moderate-High (turbo luxury sedan) · Maintenance ~$700/yr (premium fuel)",
        "popular_mods": [
            "Ecutek tune or JB4 piggyback (+40-100 whp → 350-400 whp)",
            "Catless downpipes, cold air intakes, upgraded intercoolers (FBO ~440-475 whp)",
            "E85 flex fuel + upgraded HPFP/LPFP (500+ whp on stock turbos)",
            "Coilovers + sway bars",
            "Huge tuning headroom — one of the best bang-for-buck platforms out there",
        ],
        "oil_type": "5W-30 or 5W-40 full synthetic",
        "oil_interval": "Every 5,000 miles (recommended — do not stretch intervals on a turbo)",
        "generations": {
            "2016–2017 (VR30 Introduction)": "3.7L replaced by 3.0L twin-turbo VR30DDTT. 300hp and 400hp (Red Sport) variants introduced. 2nd-gen Direct Adaptive Steering.",
            "2018–2023 (Refresh)": "Visual refresh unveiled at 2017 Geneva Motor Show. Improved interior quality, clearer trim levels, added driver-assistance tech. Base 2.0T four-cylinder added.",
            "2024 (Final Year)": "Infiniti announced discontinuation in August 2024. Last model year for US and Canada after 11 years. Slow sales ended the run.",
        },
        "common_issues": [
            "Wastegate rattle — pivot point wears inside turbo housing",
            "Valve body issues and rear differential bushing wear at high mileage",
            "Oil consumption if intervals are extended",
        ],
        "maintenance_tips": [
            "Do not extend oil changes past 5,000 miles — turbos are oil-dependent",
            "Change transmission fluid every 30-40k miles (Infiniti says lifetime — ignore that)",
            "Monitor coolant level — turbocharged engines are harder on cooling systems",
        ],
    },
    "Infiniti Q50 Red Sport 400": {
        "engine": "3.0L twin-turbo V6 (VR30DDTT — high output)",
        "horsepower": 400,
        "torque": "350 lb-ft",
        "drivetrain": "RWD / AWD",
        "transmission": "7-speed automatic",
        "0_to_60": "4.5 sec",
        "fuel_economy": "20 city / 26 hwy mpg (RWD)",
        "curb_weight": "3,890 lbs",
        "reliability": "6/10 — same VR30 under more stress; DAS steering quirks knock points off",
        "cost_to_own": "Insurance: High (400hp luxury sport sedan) · Maintenance ~$750/yr (premium fuel, perf brakes/tires)",
        "popular_mods": [
            "Ecutek/JB4 tune (430+ whp with tune alone on the high-output VR30)",
            "Full bolt-ons (downpipes/intakes/intercoolers) ~475 whp",
            "E85 + fuel system upgrades = 500-525 whp on stock turbos",
            "Coilovers, sway bars, big brake kit",
            "Best starting point in the Q50 range for a serious power build",
        ],
        "oil_type": "5W-30 or 5W-40 full synthetic",
        "oil_interval": "Every 5,000 miles",
        "generations": {
            "2016–2017 (Launch)": "Introduced alongside the 3.0t. 400hp from same VR30DDTT block with higher boost. Standard steer-by-wire DAS — controversial among enthusiasts.",
            "2018–2023 (Refresh)": "Same refresh as the 3.0t. More aggressive Red Sport-specific styling cues and Brembo brakes. Interior quality improved significantly.",
            "2024 (Final Year)": "Last production year. Discontinued alongside full Q50 lineup. Used copies remain one of the best performance sedan values on the used market.",
        },
        "common_issues": [
            "Steer-by-wire (DAS) feels numb — no road feedback at low speeds",
            "Wastegate rattle (same as 3.0t — turbo housing wear)",
            "Firm suspension transmits road harshness into the cabin",
        ],
        "maintenance_tips": [
            "Same engine as 3.0t — follow same strict 5k oil change interval",
            "DAS system can be replaced with a conventional rack if preferred",
            "Inspect turbo boost hoses for cracks — high output puts more stress on them",
        ],
    },
    "Nissan 370Z": {
        "engine": "3.7L V6 (VQ37VHR)",
        "horsepower": 332,
        "torque": "270 lb-ft",
        "drivetrain": "RWD",
        "transmission": "6-speed manual (SynchroRev Match) / 7-speed auto",
        "0_to_60": "5.1 sec",
        "fuel_economy": "18 city / 26 hwy mpg",
        "curb_weight": "3,463 lbs",
        "reliability": "7/10 — strong VQ engine, but the clutch slave cylinder failure is a real black mark",
        "cost_to_own": "Insurance: Moderate-High (sports coupe) · Maintenance ~$550/yr",
        "popular_mods": [
            "Intake, high-flow cats / test pipes, catback exhaust",
            "Uprev or Ecutek ECU tune (modest NA gains)",
            "Forced induction (turbo/supercharger kits) for serious power",
            "Coilovers, sway bars, big brake kit",
            "Nismo suspension and aero parts",
        ],
        "oil_type": "5W-30 full synthetic (Nissan Ester oil recommended)",
        "oil_interval": "Every 5,000 miles (3,750 under hard/track use)",
        "generations": {
            "350Z (Z33, 2003–2008)": "Predecessor. 3.5L VQ35 V6 (287–306hp). The car that revived the Z nameplate in the US.",
            "370Z (Z34, 2009–2020)": "3.7L VQ37VHR, 332hp. World's first manual with SynchroRev Match. Long 12-year run with minimal changes. Nismo trim made 350hp.",
            "Nissan Z (RZ34, 2023–present)": "Successor. 3.0L twin-turbo VR30DDTT, 400hp (shared with Q50 Red Sport). Dropped the displacement-based name.",
        },
        "common_issues": [
            "Concentric slave cylinder (CSC) failure — cheap plastic part, requires transmission removal ($1,500-$3,500)",
            "Oil consumption (shared VQ trait) at higher mileage",
            "Rear tire wear from aggressive factory camber",
            "Notchy 2nd-gear synchro when cold",
        ],
        "maintenance_tips": [
            "Replace the plastic CSC with an aftermarket metal unit proactively",
            "Use Nissan ester oil and check level regularly",
            "Get an alignment to slow rear tire wear",
            "Let the gearbox warm up before hard 2nd-gear shifts",
        ],
    },
    "BMW M3": {
        "engine": "3.0L twin-turbo I6 (S58)",
        "horsepower": 503,
        "torque": "479 lb-ft (G80 Competition)",
        "drivetrain": "RWD / AWD (xDrive)",
        "transmission": "6-speed manual / 8-speed auto",
        "0_to_60": "3.4 sec (Competition xDrive)",
        "fuel_economy": "16 city / 23 hwy mpg",
        "curb_weight": "3,900 lbs",
        "reliability": "6/10 — thrilling but high-strung; every generation has a signature expensive failure",
        "cost_to_own": "Insurance: Very High (high-performance luxury) · Maintenance ~$1,300/yr",
        "popular_mods": [
            "ECU tune — huge gains on turbo S55/S58 (500+ whp easily achievable)",
            "Downpipes, intake, charge pipe, upgraded intercooler (S55/S58)",
            "NA cars (S54/S65): headers + tune, or supercharger for big power",
            "Coilovers, sway bars, big brake kit",
            "Preventive crank hub fix (F80) / rod bearing refresh (E46/E90)",
        ],
        "oil_type": "10W-60 (S54/S65) / 0W-30 (S55/S58) full synthetic",
        "oil_interval": "Every 5,000-7,500 miles (BMW's 10k+ interval is too long for these engines)",
        "generations": {
            "E46 (2000–2006)": "3.2L S54 inline-6, 333hp, 8,000rpm redline. A high point of the breed. 6-speed manual or clunky SMG. Watch rod bearings and rear subframe cracking.",
            "E90/E92/E93 (2008–2013)": "4.0L S65 V8, 414hp, 8,400rpm redline — the only V8 M3. Sedan/coupe/vert. Rod bearings and throttle actuators are the weak spots.",
            "F80 (2014–2018)": "3.0L S55 twin-turbo inline-6, 425hp (Competition 444hp). First turbo M3 — torque leapt to 406 lb-ft. Infamous crank hub slip.",
            "G80 (2021–present)": "3.0L S58 twin-turbo inline-6, 473hp / 503hp Competition. Added xDrive AWD. Controversial oversized grille. Manual still offered on base RWD.",
        },
        "common_issues": [
            "Rod bearing failure (E46 S54, E90 S65) — factory clearances too tight; preventive replacement advised",
            "Rear subframe mounting points crack (E46)",
            "Crank hub slipping (F80 S55) — secured by a single friction bolt",
            "Throttle actuator failure (E90 S65)",
        ],
        "maintenance_tips": [
            "Budget for preventive rod bearing replacement on E46/E90",
            "Install a crank hub fix on F80 before tuning for higher power",
            "Shorten oil intervals well below BMW's recommendation",
            "Inspect E46 rear subframe for cracks at the chassis mounts",
        ],
    },
    "Dodge Charger R/T / Scat Pack": {
        "engine": "6.4L 392 HEMI V8 (Scat Pack) / 5.7L HEMI V8 (R/T)",
        "horsepower": 485,
        "torque": "475 lb-ft (Scat Pack) / 395 lb-ft (R/T)",
        "drivetrain": "RWD",
        "transmission": "8-speed automatic",
        "0_to_60": "4.3 sec (Scat Pack) / 5.5 sec (R/T)",
        "fuel_economy": "15 city / 24 hwy mpg (Scat Pack)",
        "curb_weight": "4,360 lbs (Scat Pack)",
        "reliability": "7/10 — simple, robust HEMI V8s, but the MDS lifter tick can escalate to cam damage",
        "cost_to_own": "Insurance: High (V8 muscle) · Maintenance ~$650/yr (premium fuel, thirsty)",
        "popular_mods": [
            "Cold air intake + 87/93-octane PCM tune (DiabloSport / HP Tuners)",
            "Long-tube headers + catback exhaust",
            "Supercharger (Whipple / ProCharger) for big power",
            "Lowering springs, sway bars, drag radials",
            "Upgraded lifters/cam or MDS delete on a rebuild",
        ],
        "oil_type": "5W-20 (5.7) / 0W-40 (6.4) full synthetic",
        "oil_interval": "Every 5,000-6,000 miles (don't stretch — sludge starves the MDS lifters)",
        "generations": {
            "LX (2006–2010)": "Modern Charger revived as a 4-door muscle sedan. SRT8 ran a 6.1L HEMI. RWD or AWD.",
            "LD (2011–2023)": "Refreshed platform. R/T (5.7), Scat Pack (6.4/392), SRT Hellcat (6.2 supercharged, 707-717hp). The last of the HEMI Chargers.",
            "LB Daytona (2024–present)": "All-new — electric Charger Daytona plus twin-turbo inline-6 'Hurricane' SIXPACK versions replacing the HEMI. Now offered as a 2-door and 4-door.",
        },
        "common_issues": [
            "HEMI MDS lifter tick → collapsed lifters and camshaft damage if ignored",
            "Exhaust manifold bolt breakage (exhaust tick on cold start)",
            "Thirsty — real-world fuel economy is low",
            "Heavy curb weight blunts agility versus lighter rivals",
        ],
        "maintenance_tips": [
            "Change oil every 5-6k with the correct spec to keep MDS oil passages clean",
            "Address any lifter tick immediately before it wipes the camshaft",
            "Inspect/replace exhaust manifold bolts if you hear a cold-start tick",
            "Run premium fuel in the 392/Scat Pack",
        ],
    },
    "Honda Civic Type R": {
        "engine": "2.0L turbo I4 (K20C1)",
        "horsepower": 315,
        "torque": "310 lb-ft (FL5)",
        "drivetrain": "FWD",
        "transmission": "6-speed manual (only)",
        "0_to_60": "4.9 sec",
        "fuel_economy": "22 city / 28 hwy mpg",
        "curb_weight": "3,150 lbs",
        "reliability": "8/10 — robust K20C turbo and Honda bones; track abuse exposes gearbox and cooling limits",
        "cost_to_own": "Insurance: High (performance hatch, theft target, dealer markups) · Maintenance ~$450/yr",
        "popular_mods": [
            "Hondata FlashPro tune (+40-60 whp)",
            "Intake, downpipe, catback exhaust, upgraded front-mount intercooler",
            "Big brake pads + high-temp fluid for track days",
            "Lightweight wheels + R-compound tires",
            "Reinforced 3rd/4th gears for heavily tracked cars",
        ],
        "oil_type": "0W-20 full synthetic",
        "oil_interval": "Every 5,000-6,000 miles (sooner with track use)",
        "generations": {
            "EK9 / EP3 / FD2 (1997–2010)": "JDM/Euro icons (B16B, K20A) — naturally aspirated, high-revving legends. Never sold new in the US.",
            "FK2 (2015–2017)": "First turbocharged Type R, 306hp K20C1. Europe and Japan only.",
            "FK8 (2017–2021)": "First US-market CTR. 306hp, set the FWD Nürburgring lap record. Bold boy-racer styling. Watch fuel pump and 3rd/4th gear on tracked cars.",
            "FL5 (2023–present)": "315hp, 15% stiffer chassis, more mature looks. Reclaimed the FWD 'Ring record. Widely called the best-driving CTR yet.",
        },
        "common_issues": [
            "FK8 in-tank fuel pump failure (recalled) — rev-match/emissions codes",
            "3rd/4th gear failure on heavily tracked FK8s (reinforced gears available)",
            "Track overheating → limp mode (notably FL5)",
            "Clutch wear if driven hard; rev-hang on upshifts (both gens)",
        ],
        "maintenance_tips": [
            "Confirm the FK8 fuel pump recall was completed on used examples",
            "Track use: add oil/diff cooling and monitor temps to avoid limp mode",
            "Upgrade brake fluid and pads before track days",
            "Check oil for dilution in cold climates (shared K-series turbo trait)",
        ],
    },
    "Mazda MX-5 Miata": {
        "engine": "2.0L Skyactiv I4 (ND)",
        "horsepower": 181,
        "torque": "151 lb-ft (ND)",
        "drivetrain": "RWD",
        "transmission": "6-speed manual / 6-speed auto",
        "0_to_60": "5.7 sec",
        "fuel_economy": "26 city / 34 hwy mpg",
        "curb_weight": "2,345 lbs",
        "reliability": "9/10 — engines are nearly impossible to kill; rust on older cars is the real enemy",
        "cost_to_own": "Insurance: Low-Moderate (cheap, low-power 2-seater) · Maintenance ~$430/yr",
        "popular_mods": [
            "Coilovers, sway bars, fresh bushings — the soul of Miata modding",
            "Lightweight wheels + sticky 200-treadwear tires",
            "Header, intake, catback exhaust (modest NA power gains)",
            "Forced induction (turbo/supercharger kits) for real power",
            "Hardtop + roll bar for track duty",
        ],
        "oil_type": "0W-20 (ND) / 5W-30 (older) full synthetic",
        "oil_interval": "Every 5,000-7,500 miles",
        "generations": {
            "NA (1990–1997)": "1.6L (116hp) then 1.8L (128hp). ~2,100 lbs, pop-up headlights, near 50:50 balance. The original that defined the modern roadster.",
            "NB (1999–2005)": "1.8L, up to 142hp. Fixed headlights, 6-speed available. Still belt-driven (replace every 60k).",
            "NC (2006–2015)": "2.0L MZR, 170hp. Larger and ~2,480 lbs. Power retractable hardtop (PRHT) offered. Early '06 cars had rod-bearing engine failures.",
            "ND (2016–present)": "2.0L Skyactiv, 155hp early → 181hp (2019+). Back to ~2,340 lbs lightweight ethos. RF retractable fastback option.",
        },
        "common_issues": [
            "Rust on rocker panels and fender arches (NA/NB worst; NC improved)",
            "Cooling system plastic parts crack → coolant leaks (NA/NB)",
            "Early 2006 NC rod-bearing / engine failures",
            "Soft top and window seals wear with age",
        ],
        "maintenance_tips": [
            "Inspect rockers, arches, and frame rails for rust before buying older cars",
            "NA/NB: replace the timing belt every 60k miles (NC/ND use a maintenance-free chain)",
            "Refresh cooling-system plastics on NA/NB to prevent leaks",
            "Keep up with oil changes — these engines last forever if maintained",
        ],
    },
    "Toyota GR Supra": {
        "engine": "3.0L turbo I6 (B58, BMW-sourced)",
        "horsepower": 382,
        "torque": "368 lb-ft",
        "drivetrain": "RWD",
        "transmission": "8-speed auto / 6-speed manual (2023+)",
        "0_to_60": "3.9 sec",
        "fuel_economy": "22 city / 30 hwy mpg",
        "curb_weight": "3,300 lbs (3,400 manual)",
        "reliability": "8/10 — B58 is among BMW's toughest modern engines; some early oil consumption, but Toyota-like in practice",
        "cost_to_own": "Insurance: High (380hp sports coupe) · Maintenance ~$900/yr (BMW mechanicals, Toyota service network)",
        "popular_mods": [
            "ECU tune (JB4 piggyback or MHD/bootmod3 flash) — 450-500+ whp potential",
            "Downpipe, intake, charge pipe, upgraded intercooler",
            "E85 for big power on the stock turbo (500+ whp)",
            "Coilovers, sway bars, big brake kit",
            "Bigger turbo for 600+ whp builds",
        ],
        "oil_type": "0W-20 full synthetic (BMW LL-spec)",
        "oil_interval": "Every 5,000-7,500 miles (BMW's 10k+ interval is too long)",
        "generations": {
            "A40/A60 (1978–1986)": "Celica Supra — the inline-six GT origins of the nameplate.",
            "A70 (1986–1993)": "First standalone Supra. Turbo 7M-GTE inline-six.",
            "A80 (1993–2002)": "Legendary 2JZ-GTE twin-turbo — 320hp stock, 1,000hp+ capable. The car that built the Supra legend.",
            "A90/A91 (2020–present)": "Revived after 17 years. BMW-derived B58 3.0 inline-six (335→382hp) and B48 2.0. Co-developed with BMW (Z4 sibling), built by Magna Steyr. Manual added 2023; Final Edition up to 429hp.",
        },
        "common_issues": [
            "Early-year oil consumption (piston rings) with occasional limp mode",
            "Highway-speed steering shudder (usually wheel balance/alignment)",
            "Wind buffeting with windows down (cheap deflector fix)",
            "It's BMW underneath — electronics, interior, and engine are BMW-sourced",
        ],
        "maintenance_tips": [
            "Shorten oil intervals below BMW's 10k recommendation",
            "Use BMW LL-spec oil — the B58 is particular",
            "Balance and align wheels to cure highway steering shudder",
            "Huge tuning headroom, but upgrade fueling before chasing big power",
        ],
    },
    "Volkswagen Golf GTI": {
        "engine": "2.0L turbo I4 (EA888)",
        "horsepower": 241,
        "torque": "273 lb-ft (Mk8)",
        "drivetrain": "FWD",
        "transmission": "6-speed manual / 7-speed DSG",
        "0_to_60": "5.6 sec",
        "fuel_economy": "24 city / 33 hwy mpg",
        "curb_weight": "3,150 lbs",
        "reliability": "7/10 — EA888 is strong and long-lived, but water pump, carbon buildup, and DSG service are watch items",
        "cost_to_own": "Insurance: Moderate (practical hot hatch) · Maintenance ~$630/yr (VW parts/labor)",
        "popular_mods": [
            "APR / Unitronic / Cobb Stage 1 ECU tune (290-300+ hp)",
            "Intake, downpipe, upgraded intercooler",
            "DSG/transmission tune for faster shifts",
            "Lowering springs or coilovers + rear sway bar (tames understeer/torque steer)",
            "Walnut blasting as preventive maintenance",
        ],
        "oil_type": "0W-20 / 5W-40 full synthetic (VW 504.00 spec)",
        "oil_interval": "Every 5,000-7,500 miles (don't follow VW's 10k LongLife interval)",
        "generations": {
            "Mk1 (1976–1983)": "The original GTI — it invented the hot hatch.",
            "Mk5 (2006–2009)": "Return to form after the soft Mk3/Mk4 era. 2.0T FSI.",
            "Mk6 (2010–2014)": "Refined Mk5 on the same platform. 2.0T, widely loved.",
            "Mk7 (2015–2021)": "EA888 Gen3, 210→228hp (US). Often called the GTI sweet spot — sharp chassis, available manual, analog feel.",
            "Mk8 (2022–present)": "241hp EA888 evo4. Quicker but controversial touch-capacitive controls and laggy infotainment. Manual dropped after 2024 in the US.",
        },
        "common_issues": [
            "Plastic water pump / thermostat housing cracks and leaks (~50k miles)",
            "Carbon buildup on intake valves (direct injection)",
            "DSG mechatronic/clutch wear if fluid isn't serviced",
            "Mk8 buggy infotainment and frustrating touch controls",
        ],
        "maintenance_tips": [
            "Walnut-blast intake valves every 40-60k miles",
            "Replace the plastic water pump/thermostat proactively around 60-80k",
            "Service the DSG fluid every ~40k miles",
            "Use VW 504.00 oil and shorten the LongLife interval to 5-7.5k",
        ],
    },
}

choice = input("What car are you researching? ")
car = cars.get(choice)

if car is None:
    print("I don't have data on that car yet.")
else:
    print(f"\n{'=' * 40}")
    print(f"  {choice}")
    print(f"{'=' * 40}")
    print(f"  Engine:       {car['engine']}")
    print(f"  Horsepower:   {car['horsepower']} hp")
    print(f"  Torque:       {car['torque']}")
    print(f"  Drivetrain:   {car['drivetrain']}")
    print(f"  Transmission: {car['transmission']}")
    print(f"  0-60 mph:     {car['0_to_60']}")
    print(f"  Fuel Economy: {car['fuel_economy']}")
    print(f"  Curb Weight:  {car['curb_weight']}")
    print(f"  Reliability:  {car['reliability']}")
    print(f"  Cost to Own:  {car['cost_to_own']}")
    print(f"\n  Oil Type:     {car['oil_type']}")
    print(f"  Oil Interval: {car['oil_interval']}")
    print(f"\n  Generation History:")
    for gen, notes in car["generations"].items():
        print(f"    {gen}")
        print(f"      {notes}")
    print(f"\n  Common Issues:")
    for issue in car["common_issues"]:
        print(f"    - {issue}")
    print(f"\n  Maintenance Tips:")
    for tip in car["maintenance_tips"]:
        print(f"    - {tip}")
    print(f"\n  Popular Mods:")
    for mod in car["popular_mods"]:
        print(f"    - {mod}")
