"""Generate data/catalog.json: a lightweight catalog of popular enthusiast cars.

WHY THIS EXISTS
---------------
The full per-car JSON in data/cars/ carries 16 hand-researched fields. We do NOT
hand-write those for hundreds of cars - that would mean inventing specs, which
the project explicitly forbids (data lives in APIs, not the AI's memory).

Instead, this catalog stores only RELIABLE, low-risk facts: make, model, a
representative model year, generation label, body style, and a short enthusiast
note. Everything else (recalls, complaints, safety, and later real specs) is
filled in on demand by the data engine (car_profile.build_profile) when a user
opens the car. Each catalog entry links to /profile?make=&model=&year=.

The list lives here as compact tuples so it is easy to read, review, and grow
toward 500 in batches. Run:  ./.venv/bin/python scripts/build_catalog.py
"""

import json
import os

# (make, model, year, generation, body, note)
# - model is kept close to NHTSA's naming so the engine can look it up.
# - year is one representative model year inside the generation (for the lookup).
# - notes are qualitative enthusiast color (engine codes/character), never specs.
CARS = [
    # --- Japanese: Toyota / Lexus / Scion ---
    ("Toyota", "Supra", 1997, "A80 (Mk4)", "Coupe", "2JZ-GTE inline-six tuner legend"),
    ("Toyota", "Supra", 1989, "A70 (Mk3)", "Coupe", "Turbo 7M-GTE grand tourer"),
    ("Toyota", "GR Supra", 2021, "A90", "Coupe", "Reborn on BMW B58 power"),
    ("Toyota", "GR86", 2022, "ZN8", "Coupe", "Rev-happy boxer, perfect balance"),
    ("Toyota", "GR Corolla", 2023, "E210", "Hatch", "Three-cylinder rally hatch"),
    ("Toyota", "MR2", 1993, "SW20", "Coupe", "Mid-engine turbo wedge"),
    ("Toyota", "MR2 Spyder", 2002, "ZZW30", "Roadster", "Lightweight mid-engine roadster"),
    ("Toyota", "Celica", 1994, "GT-Four ST205", "Coupe", "Turbo AWD rally homologation"),
    ("Toyota", "Corolla", 1985, "AE86", "Coupe", "Drift icon, 4A-GE"),
    ("Scion", "FR-S", 2013, "ZN6", "Coupe", "The original 86 in the US"),
    ("Lexus", "IS300", 2003, "XE10", "Sedan", "2JZ sedan, manual available"),
    ("Lexus", "IS F", 2010, "XE20", "Sedan", "5.0 V8 sleeper sedan"),
    ("Lexus", "LFA", 2011, "LFA", "Coupe", "Screaming 4.8 V10 halo car"),
    ("Lexus", "RC F", 2016, "XC10", "Coupe", "Naturally aspirated V8 coupe"),

    # --- Japanese: Nissan / Infiniti ---
    ("Nissan", "GT-R", 2017, "R35", "Coupe", "Twin-turbo VR38 giant-killer"),
    ("Nissan", "Skyline GT-R", 1999, "R34", "Coupe", "RB26 legend, import icon"),
    ("Nissan", "Skyline GT-R", 1993, "R32", "Coupe", "Godzilla, AWD RB26"),
    ("Nissan", "240SX", 1991, "S13", "Coupe", "Drift staple, SR swap favorite"),
    ("Nissan", "240SX", 1997, "S14", "Coupe", "Later drift-build staple"),
    ("Nissan", "300ZX", 1994, "Z32", "Coupe", "Twin-turbo VG30DETT GT"),
    ("Nissan", "350Z", 2005, "Z33", "Coupe", "VQ35 affordable RWD coupe"),
    ("Nissan", "370Z", 2015, "Z34", "Coupe", "VQ37 raw analog coupe"),
    ("Nissan", "Z", 2023, "RZ34", "Coupe", "Twin-turbo VR30 revival"),
    ("Nissan", "Sentra", 2005, "SE-R Spec V", "Sedan", "QR25 budget sport sedan"),
    ("Infiniti", "G35", 2005, "V35", "Coupe", "VQ35 RWD enthusiast bargain"),
    ("Infiniti", "G37", 2010, "V36", "Coupe", "VQ37 sharper sport coupe"),
    ("Infiniti", "Q60", 2017, "V37", "Coupe", "VR30 twin-turbo grand tourer"),

    # --- Japanese: Mazda ---
    ("Mazda", "RX-7", 1993, "FD", "Coupe", "Sequential-turbo 13B rotary"),
    ("Mazda", "RX-7", 1991, "FC", "Coupe", "Turbo rotary, 80s icon"),
    ("Mazda", "RX-8", 2005, "SE3P", "Coupe", "Renesis rotary, suicide doors"),
    ("Mazda", "MX-5 Miata", 1994, "NA", "Roadster", "The roadster that saved roadsters"),
    ("Mazda", "MX-5 Miata", 2001, "NB", "Roadster", "Refined second-gen Miata"),
    ("Mazda", "MX-5 Miata", 2008, "NC", "Roadster", "Bigger, available PRHT"),
    ("Mazda", "MX-5 Miata", 2016, "ND", "Roadster", "Back-to-basics lightweight Skyactiv roadster"),
    ("Mazdaspeed", "Mazdaspeed3", 2010, "BL", "Hatch", "Torque-steering turbo hatch"),
    ("Mazdaspeed", "Mazdaspeed6", 2006, "GG", "Sedan", "AWD turbo sport sedan"),

    # --- Japanese: Honda / Acura ---
    ("Honda", "S2000", 2004, "AP1/AP2", "Roadster", "9k-rpm F20C/F22C roadster"),
    ("Honda", "NSX", 1995, "NA1", "Coupe", "Senna-honed mid-engine VTEC"),
    ("Acura", "NSX", 2017, "NC1", "Coupe", "Twin-turbo hybrid supercar"),
    ("Honda", "Prelude", 1999, "BB6", "Coupe", "VTEC coupe with ATTS"),
    ("Honda", "CRX", 1988, "EF", "Hatch", "Featherweight VTEC tuner base"),
    ("Acura", "Integra Type R", 1998, "DC2", "Coupe", "B18C5, FWD benchmark"),
    ("Acura", "RSX Type S", 2005, "DC5", "Coupe", "K20 high-revving coupe"),
    ("Acura", "Integra", 2023, "DE4", "Hatch", "Modern Type S revival"),
    ("Honda", "Civic Type R", 2023, "FL5", "Hatch", "FWD lap-record hatch"),
    ("Honda", "Civic Si", 1994, "5th Gen EG", "Hatch", "D16Z6, first VTEC Si"),
    ("Honda", "Civic Si", 1999, "6th Gen EM1", "Coupe", "B16A2, cult EM1 coupe"),
    ("Honda", "Civic Si", 2003, "7th Gen EP3", "Hatch", "K20A3, first i-VTEC Si"),
    ("Honda", "Civic Si", 2007, "8th Gen FG2", "Coupe", "K20Z3, helical LSD"),
    ("Honda", "Civic Si", 2008, "8th Gen FA5", "Sedan", "K20Z3, four-door Si"),
    ("Honda", "Civic Si", 2014, "9th Gen FG4", "Coupe", "K24Z7 2.4L, last NA Si"),
    ("Honda", "Civic Si", 2013, "9th Gen FB6", "Sedan", "K24Z7 2.4L NA, four-door"),
    ("Honda", "Civic Si", 2018, "10th Gen FC3", "Coupe", "L15B7 turbo, last Si coupe"),
    ("Honda", "Civic Si", 2019, "10th Gen FC1", "Sedan", "L15B7 turbo return"),
    ("Honda", "Civic Si", 2022, "11th Gen FE1", "Sedan", "L15CA turbo, low-rpm torque"),

    # --- Japanese: Subaru / Mitsubishi ---
    ("Subaru", "WRX STI", 2015, "VA", "Sedan", "EJ257 rally-bred AWD turbo"),
    ("Subaru", "BRZ", 2022, "ZD8", "Coupe", "Boxer twin to the GR86"),
    ("Subaru", "Legacy", 2007, "GT spec.B", "Sedan", "Sleeper turbo wagon/sedan"),
    ("Mitsubishi", "Lancer", 2006, "Evolution IX", "Sedan", "4G63 rally homologation"),
    ("Mitsubishi", "Lancer", 2010, "Evolution X", "Sedan", "4B11T final Evo"),
    ("Mitsubishi", "3000GT", 1994, "VR-4", "Coupe", "Twin-turbo AWD tech flagship"),
    ("Mitsubishi", "Eclipse", 1997, "GSX 2G", "Coupe", "4G63 turbo AWD DSM"),

    # --- German: BMW ---
    ("BMW", "M3", 1990, "E30", "Coupe", "S14 motorsport homologation"),
    ("BMW", "M3", 1997, "E36", "Coupe", "Inline-six everyday M car"),
    ("BMW", "M3", 2003, "E46", "Coupe", "S54, the enthusiast benchmark"),
    ("BMW", "M3", 2010, "E92", "Coupe", "S65 V8 high-revving M3"),
    ("BMW", "M2", 2018, "F87", "Coupe", "Compact rear-drive enthusiast M"),
    ("BMW", "M4", 2015, "F82", "Coupe", "S55 twin-turbo coupe"),
    ("BMW", "M5", 2002, "E39", "Sedan", "S62 V8 super-sedan icon"),
    ("BMW", "M5", 2007, "E60", "Sedan", "S85 V10 F1-inspired sedan"),
    ("BMW", "1 Series M", 2011, "E82", "Coupe", "N54 cult classic 1M"),
    ("BMW", "335i", 2010, "E92", "Coupe", "N54 tuner-favorite twin-turbo"),
    ("BMW", "Z4 M", 2008, "E86", "Coupe", "S54 clownshoe coupe"),

    # --- German: Audi / Mercedes / VW / Porsche ---
    ("Audi", "RS4", 2007, "B7", "Sedan", "4.2 V8 quattro super-sedan"),
    ("Audi", "S4", 2001, "B5", "Sedan", "2.7 biturbo tuner favorite"),
    ("Audi", "TT RS", 2018, "8S", "Coupe", "Five-cylinder turbo coupe"),
    ("Audi", "R8", 2010, "Type 42", "Coupe", "V8/V10 everyday supercar"),
    ("Audi", "RS3", 2018, "8V", "Sedan", "Warbling five-cylinder sedan"),
    ("Mercedes-Benz", "C63 AMG", 2010, "W204", "Sedan", "6.2 M156 V8 super-sedan"),
    ("Mercedes-Benz", "190E", 1990, "2.5-16 Cosworth", "Sedan", "Cosworth-built DTM homologation"),
    ("Mercedes-Benz", "AMG GT", 2017, "C190", "Coupe", "Front-mid V8 GT"),
    ("Volkswagen", "Golf R", 2018, "Mk7", "Hatch", "AWD turbo everyday rocket"),
    ("Volkswagen", "Golf GTI", 2012, "Mk6", "Hatch", "The benchmark hot hatch"),
    ("Volkswagen", "Jetta", 2014, "GLI Mk6", "Sedan", "GTI in sedan form"),
    ("Volkswagen", "Corrado", 1992, "VR6", "Coupe", "VR6 cult-classic coupe"),
    ("Porsche", "911", 2007, "997 Carrera", "Coupe", "Flat-six everyday icon"),
    ("Porsche", "911", 2021, "992 Carrera", "Coupe", "Modern turbo flat-six 911"),
    ("Porsche", "911 GT3", 2018, "991.2", "Coupe", "NA 4.0 track weapon"),
    ("Porsche", "Cayman", 2014, "981", "Coupe", "Mid-engine driver's coupe"),
    ("Porsche", "Cayman GT4", 2020, "982", "Coupe", "NA flat-six mid-engine GT4"),
    ("Porsche", "Boxster", 2013, "981", "Roadster", "Mid-engine flat-six roadster"),
    ("Porsche", "944", 1988, "944 Turbo", "Coupe", "Transaxle-balanced 80s Porsche"),

    # --- American: Ford ---
    ("Ford", "Mustang", 2016, "Shelby GT350", "Coupe", "Flat-plane Voodoo V8"),
    ("Ford", "Mustang", 2020, "Shelby GT500", "Coupe", "Supercharged Predator V8"),
    ("Ford", "Mustang", 1990, "Fox-body GT", "Coupe", "5.0 pushrod drag staple"),
    ("Ford", "Mustang SVT Cobra", 2003, "Terminator", "Coupe", "Supercharged 'Terminator' legend"),
    ("Ford", "Focus RS", 2017, "Mk3", "Hatch", "AWD drift-mode hot hatch"),
    ("Ford", "Focus ST", 2015, "Mk3", "Hatch", "Torquey turbo daily hatch"),
    ("Ford", "Fiesta ST", 2016, "Mk7", "Hatch", "Tiny tossable turbo hatch"),
    ("Ford", "GT", 2006, "Mk1", "Coupe", "Supercharged modular V8 supercar"),

    # --- American: Chevrolet / GM ---
    ("Chevrolet", "Corvette", 2016, "C7 Stingray", "Coupe", "LT1 small-block sports car"),
    ("Chevrolet", "Corvette", 2008, "C6 Z06", "Coupe", "LS7 7.0 track Corvette"),
    ("Chevrolet", "Corvette", 2020, "C8 Stingray", "Coupe", "First mid-engine Corvette"),
    ("Chevrolet", "Corvette", 2002, "C5 Z06", "Coupe", "LS6 affordable performance icon"),
    ("Chevrolet", "Camaro", 2018, "ZL1", "Coupe", "Supercharged LT4 track muscle"),
    ("Chevrolet", "Cobalt SS", 2008, "Supercharged/Turbo", "Coupe", "Surprise GM sport compact"),
    ("Cadillac", "CTS-V", 2009, "Gen 2", "Sedan", "Supercharged LSA super-sedan"),
    ("Cadillac", "ATS-V", 2016, "Gen 1", "Coupe", "Twin-turbo V6 M4 rival"),
    ("Pontiac", "GTO", 2006, "Holden-based", "Coupe", "LS2 sleeper muscle coupe"),
    ("Pontiac", "Firebird", 2002, "Trans Am WS6", "Coupe", "LS1 fourth-gen F-body"),
    ("Pontiac", "Solstice", 2007, "GXP", "Roadster", "Turbo Ecotec roadster"),

    # --- American: Mopar ---
    ("Dodge", "Challenger", 2016, "Hellcat", "Coupe", "Supercharged 6.2 Hellcat V8"),
    ("Dodge", "Challenger", 2015, "R/T Scat Pack", "Coupe", "392 naturally aspirated Hemi"),
    ("Dodge", "Viper", 2003, "ZB Gen 3", "Coupe", "8.3 V10 raw American exotic"),
    ("Dodge", "Viper", 2017, "Gen 5 ACR", "Coupe", "8.4 V10 track-record ACR"),
    ("Dodge", "Neon", 2004, "SRT-4", "Sedan", "Turbo budget sport compact"),
    ("Chrysler", "300", 2008, "300C SRT8", "Sedan", "6.1 Hemi full-size muscle"),

    # --- Hot hatch / sport compact (other) ---
    ("Mini", "Cooper", 2015, "S F56", "Hatch", "Turbo go-kart hatch"),
    ("Mini", "Cooper", 2018, "JCW F56", "Hatch", "Hottest factory Mini"),
    ("Hyundai", "Veloster N", 2019, "JS", "Hatch", "Corner-carving Korean hot hatch"),
    ("Hyundai", "Elantra N", 2022, "CN7", "Sedan", "Track-ready sport sedan"),
    ("Hyundai", "Genesis Coupe", 2013, "BK", "Coupe", "Affordable turbo/V6 RWD coupe"),
    ("Kia", "Stinger", 2018, "GT CK", "Sedan", "Twin-turbo V6 fastback GT"),
    ("Genesis", "G70", 2019, "IK", "Sedan", "3.3T sport sedan sleeper"),

    # --- Lightweight / exotic enthusiast favorites ---
    ("Lotus", "Elise", 2005, "S2", "Roadster", "Featherweight mid-engine purity"),
    ("Lotus", "Exige", 2006, "S2", "Coupe", "Hardtop track-focused Elise"),
    ("Lotus", "Evora", 2017, "400/410", "Coupe", "Supercharged 2+2 mid-engine"),
    ("Alfa Romeo", "4C", 2015, "960", "Coupe", "Carbon-tub turbo featherweight"),
    ("Alfa Romeo", "Giulia", 2017, "Quadrifoglio", "Sedan", "Ferrari-derived twin-turbo V6"),
    ("Jaguar", "F-Type", 2016, "R", "Coupe", "Supercharged V8 British GT"),
    ("Nissan", "Pulsar", 1991, "GTI-R", "Hatch", "Homologation AWD turbo pocket rocket"),

    # --- Classics / vintage enthusiast icons ---
    ("Datsun", "240Z", 1972, "S30", "Coupe", "L24 long-hood Z origin"),
    ("BMW", "2002", 1972, "tii", "Coupe", "The car that made BMW"),
    ("Chevrolet", "Chevelle", 1970, "SS 454", "Coupe", "Big-block muscle pinnacle"),
    ("Plymouth", "Barracuda", 1970, "'Cuda", "Coupe", "Hemi E-body muscle icon"),
    ("Ford", "Mustang", 1969, "Boss 302", "Coupe", "Trans-Am homologation classic"),
    ("Volkswagen", "Beetle", 1968, "Type 1", "Coupe", "Air-cooled tuning canvas"),

    # --- Mainstream mix — Honda (Task 9: curated enthusiast+mainstream, brand by brand) ---
    ("Honda", "CR-V", 2019, "5th Gen (RW)", "SUV", "America's default compact SUV — sensible, spacious, Honda-tough"),
    ("Honda", "Civic", 2008, "8th Gen (FA/FG)", "Sedan", "Bulletproof R18 commuter, 200k-mile reputation"),
    ("Honda", "Civic", 2013, "9th Gen (FB)", "Sedan", "Efficient, no-drama daily compact"),
    ("Honda", "Civic", 2018, "10th Gen (FC)", "Sedan", "Turbo-era Civic — sharp, frugal, roomy"),
    ("Honda", "Civic", 2022, "11th Gen (FE)", "Sedan", "Grown-up, refined, still cheap to run"),
    ("Honda", "Accord", 2010, "8th Gen (CP/CS)", "Sedan", "Roomy K24/V6 family sedan"),
    ("Honda", "Accord", 2015, "9th Gen (CR)", "Sedan", "Earth Dreams efficiency; last of the V6"),
    ("Honda", "Accord", 2019, "10th Gen (CV)", "Sedan", "Turbo-four sport-sedan sharpness"),
    ("Honda", "Accord", 2023, "11th Gen (CY)", "Sedan", "Hybrid-led, refined commuter"),
    ("Honda", "Fit", 2018, "3rd Gen (GK)", "Hatch", "Magic-Seat subcompact — huge space, tiny thirst, 200k-mile reputation"),
    ("Honda", "HR-V", 2019, "1st Gen (RU)", "SUV", "A tall, practical Fit — sensible subcompact crossover"),
    ("Honda", "Insight", 2019, "3rd Gen (ZE4)", "Sedan", "Stealth hybrid Civic — 52 mpg without looking like an eco-box"),
    ("Honda", "Odyssey", 2018, "5th Gen (RL6)", "Minivan", "The enthusiast's minivan — quick J35 V6, Magic Slide seats"),
    ("Honda", "Pilot", 2019, "3rd Gen", "SUV", "Roomy three-row family SUV on the durable J35 V6"),

    # --- Mainstream mix — Toyota (Task 9: mainstream + economy curated coverage) ---
    ("Toyota", "Corolla", 2021, "12th Gen (E210)", "Sedan", "The default dependable compact — cheap to run, nearly impossible to kill"),
    ("Toyota", "Camry", 2020, "8th Gen (XV70)", "Sedan", "America's midsize benchmark — comfortable, efficient, bulletproof"),
    ("Toyota", "RAV4", 2021, "5th Gen (XA50)", "SUV", "America's best-selling non-truck — practical, efficient, tough"),
    ("Toyota", "Highlander", 2021, "4th Gen (XU70)", "SUV", "Roomy three-row family SUV on Toyota's proven V6/hybrid"),
    ("Toyota", "4Runner", 2021, "5th Gen (N280)", "SUV", "Old-school body-on-frame SUV — thirsty but legendarily durable"),
    ("Toyota", "Tacoma", 2020, "3rd Gen", "Truck", "The resale king of midsize trucks — durable and capable"),
    ("Toyota", "Sienna", 2021, "4th Gen (XL40)", "Minivan", "The hybrid-only minivan — a ~36 mpg family hauler"),
    ("Toyota", "Prius", 2020, "4th Gen (XW50)", "Hatch", "The hybrid that went mainstream — 50+ mpg and nearly bulletproof"),
    ("Toyota", "Avalon", 2020, "5th Gen (XX50)", "Sedan", "A plush, quick full-size sedan — a stretched, quieter Camry V6"),
    ("Toyota", "Tundra", 2022, "3rd Gen", "Truck", "Full-size truck reborn on twin-turbo V6 power"),
    ("Toyota", "Corolla Cross", 2022, "1st Gen", "SUV", "A Corolla on stilts — an efficient, affordable subcompact SUV"),
    ("Toyota", "Yaris", 2019, "Mazda2-based", "Sedan", "Cheap, durable subcompact — later US cars were rebadged Mazda2s"),

    # --- Catalog growth batch 2 (2026-07): more enthusiast + classic icons ---
    # JDM / Japanese
    ("Toyota", "Celica", 2003, "GT-S (ZZT231)", "Coupe", "2ZZ-GE high-revving FWD coupe"),
    ("Toyota", "Supra", 1985, "A60 (Mk2)", "Coupe", "5M-GE early Supra grand tourer"),
    ("Toyota", "MR2", 1988, "AW11", "Coupe", "First-gen 4A-GE mid-engine"),
    ("Toyota", "Land Cruiser", 1995, "80 Series", "SUV", "Legendary go-anywhere off-roader"),
    ("Toyota", "FJ Cruiser", 2010, "GSJ15", "SUV", "Retro body-on-frame 4x4"),
    ("Lexus", "SC 300", 1994, "Z30", "Coupe", "2JZ-GE 2+2, manual available"),
    ("Lexus", "LC 500", 2018, "Z100", "Coupe", "5.0 V8 grand-touring halo"),
    ("Lexus", "GS F", 2018, "L10", "Sedan", "Naturally aspirated 5.0 V8 super-sedan"),
    ("Nissan", "Silvia", 1999, "S15", "Coupe", "SR20DET JDM drift icon"),
    ("Nissan", "200SX", 1995, "SE-R (B14)", "Coupe", "SR20DE sport compact"),
    ("Nissan", "Maxima", 1992, "SE (J30)", "Sedan", "VE30DE '4DSC' sport sedan"),
    ("Datsun", "510", 1970, "PL510", "Sedan", "The 'poor man's BMW' rally classic"),
    ("Datsun", "280Z", 1977, "S30", "Coupe", "Fuel-injected long-hood Z"),
    ("Mazda", "RX-7", 1980, "SA22C", "Coupe", "First-gen 12A rotary"),
    ("Mazda", "323 GTX", 1988, "BF", "Hatch", "Turbo AWD rally homologation"),
    ("Mazda", "Mazdaspeed Protege", 2003, "BJ", "Sedan", "Turbo compact sport sedan"),
    ("Honda", "del Sol", 1994, "Si (EG2)", "Coupe", "VTEC targa-top"),
    ("Honda", "Civic", 1999, "EK9 Type R (JDM)", "Hatch", "JDM B16B hatch benchmark"),
    ("Honda", "Prelude", 1994, "BB1 (4th Gen)", "Coupe", "H22 VTEC coupe"),
    ("Acura", "Integra", 1999, "GS-R (DC2)", "Coupe", "B18C1 VTEC enthusiast favorite"),
    ("Acura", "TL", 2007, "Type-S (UA7)", "Sedan", "J35 VTEC sport sedan"),
    ("Acura", "Legend", 1991, "KA7/KA8", "Coupe", "C32A V6 grand tourer"),
    ("Subaru", "WRX", 2004, "GD 'Blobeye'", "Sedan", "EJ205 turbo rally sedan"),
    ("Subaru", "WRX", 2015, "VA", "Sedan", "FA20DIT turbo AWD sedan"),
    ("Subaru", "Impreza", 1999, "2.5 RS (GC8)", "Coupe", "NA enthusiast base, rally looks"),
    ("Subaru", "Forester", 2006, "XT (SG)", "SUV", "Turbo sleeper wagon-SUV"),
    ("Mitsubishi", "Lancer", 2004, "Evolution VIII", "Sedan", "4G63 turbo AWD, MR gearbox"),
    ("Mitsubishi", "Lancer", 1999, "Evolution VI", "Sedan", "4G63 Tommi Mäkinen era"),
    ("Mitsubishi", "Starion", 1988, "ESI-R", "Coupe", "Turbo four-cylinder 80s wedge"),
    ("Mitsubishi", "Galant", 1991, "VR-4", "Sedan", "4G63 turbo AWD sedan"),

    # German
    ("BMW", "M5", 1991, "E34", "Sedan", "S38 straight-six super-sedan"),
    ("BMW", "M6", 2007, "E63", "Coupe", "S85 V10 grand tourer"),
    ("BMW", "135i", 2011, "E82", "Coupe", "N54/N55 compact tuner coupe"),
    ("BMW", "M235i", 2015, "F22", "Coupe", "N55 compact driver's coupe"),
    ("BMW", "Z3 M Coupe", 2001, "E36/8", "Coupe", "S52/S54 original clownshoe"),
    ("BMW", "2002", 1974, "Turbo", "Coupe", "First turbocharged production BMW"),
    ("BMW", "850i", 1991, "E31", "Coupe", "V12 grand-touring flagship"),
    ("Audi", "S3", 2017, "8V", "Sedan", "Compact quattro turbo sedan"),
    ("Audi", "RS6 Avant", 2021, "C8", "Wagon", "Twin-turbo V8 super-wagon"),
    ("Audi", "Quattro", 1983, "Ur-Quattro", "Coupe", "Turbo five-cylinder rally legend"),
    ("Audi", "S5", 2018, "B9", "Coupe", "Turbo V6 quattro coupe"),
    ("Audi", "RS7", 2016, "C7", "Sedan", "Twin-turbo V8 fastback"),
    ("Mercedes-Benz", "E63 AMG", 2014, "W212", "Sedan", "Twin-turbo 5.5 V8 super-sedan"),
    ("Mercedes-Benz", "SLS AMG", 2011, "C197", "Coupe", "Gullwing 6.2 V8 supercar"),
    ("Mercedes-Benz", "500E", 1992, "W124", "Sedan", "Porsche-built V8 Q-ship"),
    ("Mercedes-Benz", "SL55 AMG", 2003, "R230", "Roadster", "Supercharged V8 roadster"),
    ("Volkswagen", "GTI", 2008, "Mk5", "Hatch", "FSI turbo, hot-hatch return to form"),
    ("Volkswagen", "GTI", 2015, "Mk7", "Hatch", "The modern hot-hatch benchmark"),
    ("Volkswagen", "GTI", 2022, "Mk8", "Hatch", "Latest EA888 turbo GTI"),
    ("Volkswagen", "R32", 2004, "Mk4", "Hatch", "Narrow-angle VR6 AWD cult classic"),
    ("Porsche", "911 Turbo", 1987, "930", "Coupe", "Widowmaker turbo flat-six"),
    ("Porsche", "911", 1996, "993", "Coupe", "The last air-cooled 911"),
    ("Porsche", "911 GT3 RS", 2019, "991.2", "Coupe", "NA 4.0 flat-six track special"),
    ("Porsche", "911 Turbo", 2016, "991", "Coupe", "All-weather twin-turbo icon"),
    ("Porsche", "928", 1987, "S4", "Coupe", "Front-V8 grand tourer"),
    ("Porsche", "Cayman GT4 RS", 2022, "982", "Coupe", "GT3-engined mid-engine RS"),

    # American
    ("Ford", "Mustang", 2011, "GT (S197 5.0)", "Coupe", "Coyote 5.0 modern muscle"),
    ("Ford", "Mustang", 2018, "GT (S550)", "Coupe", "Coyote 5.0, IRS chassis"),
    ("Ford", "Mustang", 1996, "SVT Cobra (SN95)", "Coupe", "4.6 DOHC modular Cobra"),
    ("Ford", "Mustang", 2021, "Mach 1", "Coupe", "Track-tuned naturally aspirated Coyote"),
    ("Ford", "Taurus SHO", 1993, "Gen 1", "Sedan", "Yamaha V6 sleeper sedan"),
    ("Ford", "F-150 Raptor", 2019, "2nd Gen", "Truck", "High-speed desert-runner truck"),
    ("Ford", "GT40", 1966, "Mk II", "Coupe", "Le Mans-winning race icon"),
    ("Chevrolet", "Camaro", 2016, "SS (6th Gen)", "Coupe", "LT1 Alpha-platform muscle"),
    ("Chevrolet", "Camaro", 2014, "Z/28 (5th Gen)", "Coupe", "LS7 track-focused Camaro"),
    ("Chevrolet", "Camaro", 1988, "IROC-Z", "Coupe", "TPI third-gen F-body"),
    ("Chevrolet", "Camaro", 1969, "Z/28", "Coupe", "First-gen small-block classic"),
    ("Chevrolet", "Corvette", 1991, "C4 ZR-1", "Coupe", "LT5 'King of the Hill'"),
    ("Chevrolet", "Corvette", 1966, "C2 Sting Ray", "Coupe", "Big-block midyear icon"),
    ("Chevrolet", "Corvette", 2023, "C8 Z06", "Coupe", "Flat-plane LT6 5.5 V8"),
    ("Chevrolet", "SS", 2015, "Holden-based", "Sedan", "LS3 V8 rear-drive sleeper sedan"),
    ("Buick", "Grand National", 1987, "GNX", "Coupe", "Turbo V6 muscle sleeper"),
    ("Pontiac", "Trans Am", 1977, "2nd Gen", "Coupe", "Bandit-era 400 V8 F-body"),
    ("Pontiac", "Fiero", 1988, "GT", "Coupe", "Mid-engine sport commuter"),
    ("Dodge", "Charger", 2016, "Hellcat", "Sedan", "Supercharged 6.2 super-sedan"),
    ("Dodge", "Charger", 2015, "R/T Scat Pack", "Sedan", "392 Hemi four-door muscle"),
    ("Dodge", "Challenger", 1970, "R/T", "Coupe", "E-body Hemi/440 classic"),
    ("Dodge", "Ram", 2005, "SRT-10", "Truck", "Viper V10-powered pickup"),
    ("Plymouth", "Road Runner", 1969, "440/Hemi", "Coupe", "Budget muscle icon"),
    ("Plymouth", "Superbird", 1970, "Hemi", "Coupe", "Winged NASCAR homologation"),
    ("Oldsmobile", "442", 1970, "W-30", "Coupe", "455 big-block A-body muscle"),
    ("AMC", "Javelin", 1971, "AMX", "Coupe", "Muscle-era pony car"),
    ("Shelby", "Cobra", 1966, "427", "Roadster", "Big-block AC Cobra legend"),

    # Hot hatch / other / EV
    ("Mini", "Cooper", 2020, "JCW GP (F56)", "Hatch", "Hardcore two-seat track Mini"),
    ("Fiat", "500", 2013, "Abarth", "Hatch", "Turbo pocket rocket with attitude"),
    ("Fiat", "124 Spider", 2017, "Abarth", "Roadster", "Turbo Miata-based roadster"),
    ("Hyundai", "Kona N", 2022, "OS", "SUV", "Hot-hatch power in a crossover"),
    ("Volvo", "850 R", 1996, "P80", "Wagon", "Turbo five-cylinder sleeper wagon"),
    ("Volvo", "S60 R", 2004, "P2", "Sedan", "AWD turbo five-cylinder sedan"),
    ("Saab", "9-3", 2002, "Viggen", "Hatch", "Torque-steering turbo Saab"),
    ("Tesla", "Model 3", 2021, "Performance", "Sedan", "Dual-motor EV sport sedan"),
    ("Tesla", "Model S", 2022, "Plaid", "Sedan", "Tri-motor sub-2-second EV"),
    ("Porsche", "Taycan", 2021, "Turbo S", "Sedan", "Launch-control EV super-sedan"),

    # --- Catalog growth batch 3 (2026-07): exotics, Euro hot hatches, more JDM,
    #     modern American performance, EV/mainstream fills ---
    # Italian exotics
    ("Ferrari", "F40", 1990, "Type F120", "Coupe", "Twin-turbo V8 poster supercar"),
    ("Ferrari", "F355", 1997, "Berlinetta", "Coupe", "Five-valve V8, gated manual"),
    ("Ferrari", "360 Modena", 2001, "Type F131", "Coupe", "3.6 V8 mid-engine Ferrari"),
    ("Ferrari", "458 Italia", 2011, "Type F142", "Coupe", "Last naturally aspirated V8 Ferrari"),
    ("Ferrari", "488 GTB", 2016, "Type F142M", "Coupe", "Twin-turbo V8 mid-engine"),
    ("Ferrari", "Testarossa", 1988, "Type F110", "Coupe", "Flat-12 wedge 80s icon"),
    ("Ferrari", "Enzo", 2003, "Type F140", "Coupe", "F1-derived V12 flagship hypercar"),
    ("Lamborghini", "Countach", 1988, "LP5000 QV", "Coupe", "Scissor-door V12 poster car"),
    ("Lamborghini", "Diablo", 1994, "VT", "Coupe", "V12 90s flagship"),
    ("Lamborghini", "Murcielago", 2006, "LP640", "Coupe", "6.5 V12 raging bull"),
    ("Lamborghini", "Gallardo", 2008, "LP560-4", "Coupe", "V10 everyday Lambo"),
    ("Lamborghini", "Huracan", 2015, "LB724", "Coupe", "5.2 V10 mid-engine"),
    ("Lamborghini", "Aventador", 2012, "LP700-4", "Coupe", "6.5 V12 flagship"),
    ("Maserati", "GranTurismo", 2010, "M145", "Coupe", "Ferrari-derived V8 GT"),
    ("Maserati", "MC20", 2022, "M240", "Coupe", "Twin-turbo Nettuno V6 supercar"),
    ("Lancia", "Delta HF Integrale", 1992, "Evoluzione", "Hatch", "Turbo AWD rally homologation legend"),

    # British sports / exotic
    ("McLaren", "F1", 1994, "F1", "Coupe", "BMW V12 central-seat hypercar"),
    ("McLaren", "720S", 2018, "P14", "Coupe", "Twin-turbo V8 Super Series"),
    ("McLaren", "MP4-12C", 2012, "MP4-12C", "Coupe", "The car that relaunched McLaren"),
    ("Aston Martin", "V8 Vantage", 2007, "VH", "Coupe", "4.3/4.7 V8 British sports coupe"),
    ("Aston Martin", "DB9", 2005, "VH GT", "Coupe", "V12 grand tourer"),
    ("Aston Martin", "Vantage", 2019, "AMR", "Coupe", "AMG-V8 modern Vantage"),
    ("Lotus", "Emira", 2023, "Type 131", "Coupe", "Last combustion Lotus"),
    ("Jaguar", "E-Type", 1965, "Series 1", "Coupe", "The most beautiful car ever made"),

    # French
    ("Alpine", "A110", 2018, "Type 128", "Coupe", "Featherweight mid-engine French GT"),
    ("Renault", "Megane RS", 2018, "Mk4", "Hatch", "Nurburgring-honed hot hatch"),
    ("Renault", "Clio Williams", 1994, "Phase 1", "Hatch", "Rally-bred 90s hot hatch"),
    ("Peugeot", "205 GTI", 1988, "1.9", "Hatch", "The definitive 80s hot hatch"),

    # More JDM
    ("Toyota", "Chaser", 1998, "JZX100", "Sedan", "1JZ-GTE drift sedan"),
    ("Toyota", "Soarer", 1994, "Z30", "Coupe", "1JZ/2JZ luxury GT (JDM Lexus SC)"),
    ("Toyota", "86", 2017, "ZN6", "Coupe", "Toyota-badged boxer coupe"),
    ("Toyota", "GR Yaris", 2021, "GXPA16", "Hatch", "Homologation three-cylinder AWD rally hatch"),
    ("Nissan", "Skyline GT-R", 1996, "R33", "Coupe", "RB26 mid-90s Godzilla"),
    ("Honda", "S660", 2016, "JW5", "Roadster", "Mid-engine turbo kei roadster"),
    ("Honda", "Beat", 1991, "PP1", "Roadster", "Mid-engine kei convertible"),
    ("Suzuki", "Cappuccino", 1993, "EA11R", "Roadster", "Turbo kei sports car"),
    ("Mazda", "Cosmo", 1992, "Eunos (JC)", "Coupe", "Triple-rotor 20B twin-turbo GT"),
    ("Subaru", "SVX", 1994, "Alcyone", "Coupe", "Flat-six Giugiaro GT"),
    ("Honda", "Civic Type R", 2018, "FK8", "Hatch", "K20C1 turbo lap-record hatch"),
    ("Honda", "Civic Type R", 2015, "FK2", "Hatch", "First turbo Type R"),
    ("Lexus", "IS 500", 2022, "XE30", "Sedan", "Naturally aspirated 5.0 V8 sleeper sedan"),

    # German additions
    ("BMW", "M2", 2023, "G87", "Coupe", "S58 last analog rear-drive M"),
    ("BMW", "M240i", 2022, "G42", "Coupe", "B58 compact driver's coupe"),
    ("BMW", "325is", 1989, "E30", "Coupe", "M20 six enthusiast classic"),
    ("BMW", "M8 Competition", 2020, "F92", "Coupe", "S63 twin-turbo V8 grand tourer"),
    ("BMW", "X5 M", 2021, "F95", "SUV", "Twin-turbo V8 super-SUV"),
    ("Mercedes-Benz", "A45 AMG", 2021, "W177", "Hatch", "Hand-built turbo-four hot hatch"),
    ("Mercedes-Benz", "G63 AMG", 2021, "W463", "SUV", "Twin-turbo V8 luxury off-roader"),
    ("Mercedes-Benz", "SLK55 AMG", 2007, "R171", "Roadster", "Naturally aspirated V8 roadster"),
    ("Audi", "RS5", 2019, "B9", "Coupe", "Twin-turbo V6 quattro coupe"),
    ("Audi", "TT", 2001, "8N", "Coupe", "Bauhaus first-gen quattro coupe"),
    ("Audi", "RS e-tron GT", 2022, "J1", "Sedan", "Dual-motor EV grand tourer"),
    ("Volkswagen", "Golf R", 2022, "Mk8", "Hatch", "AWD EA888 everyday rocket"),
    ("Porsche", "Carrera GT", 2005, "980", "Coupe", "V10 analog hypercar"),
    ("Porsche", "718 Spyder", 2020, "982", "Roadster", "NA flat-six mid-engine roadster"),
    ("Porsche", "911 GT2 RS", 2018, "991.2", "Coupe", "700hp turbo flat-six widowmaker"),
    ("Porsche", "Macan GTS", 2020, "95B", "SUV", "Sport-tuned enthusiast SUV"),

    # Modern American performance + fills
    ("Cadillac", "CT5-V Blackwing", 2022, "Gen 1", "Sedan", "Supercharged manual super-sedan"),
    ("Cadillac", "CT4-V Blackwing", 2022, "Gen 1", "Sedan", "Twin-turbo compact super-sedan"),
    ("Chevrolet", "Corvette", 2019, "C7 ZR1", "Coupe", "Supercharged LT5 755hp send-off"),
    ("Chevrolet", "Corvette", 1973, "C3 Stingray", "Coupe", "Chrome-bumper small-block Stingray"),
    ("Chevrolet", "Colorado", 2023, "ZR2 (3rd Gen)", "Truck", "Off-road turbo midsize truck"),
    ("Ford", "Bronco Raptor", 2022, "U725", "SUV", "Twin-turbo desert-running off-roader"),
    ("Ford", "F-150 Lightning", 2022, "EV", "Truck", "Dual-motor electric F-150"),
    ("Ford", "Mustang Mach-E", 2022, "GT", "SUV", "Electric performance crossover"),
    ("Ford", "Focus SVT", 2003, "Mk1", "Hatch", "Cult FWD sport hatch"),
    ("Jeep", "Grand Cherokee", 2020, "WK2 Trackhawk", "SUV", "Hellcat-powered super-SUV"),
    ("Jeep", "Wrangler", 2022, "JL Rubicon 392", "SUV", "6.4 Hemi V8 off-roader"),
    ("Ram", "1500", 2021, "DT TRX", "Truck", "Hellcat-powered desert truck"),
    ("Dodge", "Durango", 2021, "SRT Hellcat", "SUV", "Supercharged three-row muscle SUV"),
    ("GMC", "Syclone", 1991, "GMT400", "Truck", "Turbo AWD sport truck sleeper"),

    # Korean / EV / mainstream
    ("Hyundai", "Ioniq 5 N", 2025, "NE", "SUV", "Track-tuned dual-motor EV hot hatch"),
    ("Kia", "EV6 GT", 2023, "CV", "SUV", "576hp dual-motor performance EV"),
    ("Genesis", "G80", 2021, "RG3", "Sedan", "Twin-turbo luxury sport sedan"),
    ("Genesis", "GV70", 2022, "JK", "SUV", "Sport-luxury compact crossover"),
    ("Rivian", "R1T", 2022, "Launch Edition", "Truck", "Quad-motor electric adventure truck"),
    ("Lucid", "Air", 2022, "Grand Touring", "Sedan", "Long-range luxury performance EV"),
    ("Ford", "Maverick", 2022, "Hybrid", "Truck", "Cheap, efficient compact hybrid pickup"),
    ("Kia", "Telluride", 2020, "1st Gen", "SUV", "Value three-row family SUV benchmark"),
    ("Mazda", "Mazda3", 2019, "4th Gen (BP)", "Hatch", "Premium-feeling compact, available AWD/turbo"),
    ("Mazda", "CX-5", 2021, "2nd Gen (KF)", "SUV", "The enthusiast's compact crossover"),
    ("Subaru", "Outback", 2020, "6th Gen (BT)", "Wagon", "Rugged AWD do-everything wagon"),
    ("Subaru", "Crosstrek", 2021, "2nd Gen (GU)", "SUV", "Lifted AWD subcompact for the outdoors"),
    ("Nissan", "Rogue", 2021, "3rd Gen (T33)", "SUV", "Sensible compact family crossover"),
    ("Honda", "Ridgeline", 2020, "2nd Gen", "Truck", "Unibody midsize truck with car manners"),
    ("Ford", "F-150", 2021, "14th Gen", "Truck", "America's best-selling truck, now hybrid-available"),
    ("Jeep", "Wrangler", 2020, "JL", "SUV", "The definitive open-top off-roader"),

    # --- Catalog growth batch 4 (2026-07): to ~500 — deeper JDM/German/Italian/
    #     British benches, modern American + off-road/EV, Euro hot hatches, classics ---
    # JDM / Japanese
    ("Toyota", "Cressida", 1990, "MX83", "Sedan", "7M-GE inline-six sport-luxury sedan"),
    ("Toyota", "Starlet", 1992, "GT Turbo (EP82)", "Hatch", "4E-FTE turbo pocket rocket"),
    ("Toyota", "Mark II", 1994, "JZX90 Tourer V", "Sedan", "1JZ-GTE turbo drift sedan"),
    ("Toyota", "Aristo", 1998, "JZS161", "Sedan", "Twin-turbo 2JZ-GTE luxury sedan (JDM GS)"),
    ("Toyota", "Sequoia", 2023, "TRD Pro (3rd Gen)", "SUV", "i-FORCE MAX hybrid full-size off-roader"),
    ("Toyota", "Land Cruiser", 2024, "J250", "SUV", "Reborn turbo-hybrid body-on-frame icon"),
    ("Toyota", "Celica", 1992, "GT-Four (ST185)", "Coupe", "4WD turbo WRC homologation"),
    ("Toyota", "Corolla", 1990, "GT-S (AE92)", "Coupe", "4A-GE twin-cam FWD sport coupe"),
    ("Toyota", "Prius", 2001, "1st Gen (XW10)", "Sedan", "The hybrid pioneer"),
    ("Lexus", "GX", 2024, "550 (J250)", "SUV", "Twin-turbo V6 luxury off-roader"),
    ("Lexus", "RX", 2023, "500h F Sport", "SUV", "Turbo-hybrid luxury crossover"),
    ("Nissan", "Stagea", 1998, "260RS (WGNC34)", "Wagon", "RB26 Autech GT-R wagon"),
    ("Nissan", "Frontier", 2022, "Pro-4X (D41)", "Truck", "Rugged reborn midsize truck"),
    ("Nissan", "Xterra", 2010, "Pro-4X (N50)", "SUV", "Cult body-on-frame off-roader"),
    ("Nissan", "300ZX", 1986, "Z31", "Coupe", "VG30 first-gen T-top Z"),
    ("Nissan", "Leaf", 2018, "ZE1", "Hatch", "The EV that went mainstream"),
    ("Mazda", "Mazda6", 2018, "GJ", "Sedan", "Handsome midsize, available 2.5 turbo"),
    ("Mazda", "MX-6", 1993, "GE", "Coupe", "KL-DE V6 sport coupe"),
    ("Mazda", "CX-30", 2022, "Turbo (DM)", "SUV", "Premium subcompact crossover"),
    ("Mazda", "RX-3", 1973, "S102A", "Coupe", "Early 12A rotary giant-killer"),
    ("Acura", "TSX", 2006, "CL9", "Sedan", "K24 Euro-Accord sport sedan"),
    ("Acura", "CL", 2003, "Type-S (YA4)", "Coupe", "J32 VTEC luxury coupe, 6-speed"),
    ("Acura", "RDX", 2007, "Turbo (TB1)", "SUV", "Turbo SH-AWD compact crossover"),
    ("Acura", "Integra Type S", 2024, "DE5", "Hatch", "K20C1 turbo Type S revival"),
    ("Honda", "CR-Z", 2011, "ZF1", "Hatch", "Hybrid CRX-revival sport hatch"),
    ("Honda", "Element", 2007, "YH2", "SUV", "Boxy K24 utility cult classic"),
    ("Honda", "Civic", 1993, "EG6 SiR (JDM)", "Hatch", "B16A JDM hatch icon"),
    ("Subaru", "WRX", 2022, "VB", "Sedan", "FA24 turbo, latest WRX"),
    ("Subaru", "Impreza", 1998, "22B STI (GC8)", "Coupe", "The holy-grail rally homologation"),
    ("Subaru", "Baja", 2004, "Sport", "Truck", "Outback-based car-truck oddball"),
    ("Subaru", "Ascent", 2022, "WM", "SUV", "Three-row family SUV on the FA24 turbo"),
    ("Mitsubishi", "Lancer", 1995, "Evolution III (CE9A)", "Sedan", "4G63 early Evo homologation"),
    ("Mitsubishi", "Lancer", 2011, "Ralliart (CY)", "Sedan", "4B11T twin-clutch junior Evo"),
    ("Mitsubishi", "FTO", 1996, "GPX (DE3A)", "Coupe", "6A12 V6 JDM sport coupe"),
    ("Mitsubishi", "Outlander", 2022, "GN", "SUV", "Nissan-based three-row family SUV"),
    ("Suzuki", "Swift Sport", 2019, "ZC33S", "Hatch", "Featherweight budget hot hatch"),
    ("Suzuki", "Jimny", 2019, "JB74", "SUV", "Tiny cult off-roader"),

    # German
    ("BMW", "M3", 2015, "F80", "Sedan", "S55 twin-turbo return to the six"),
    ("BMW", "M3", 2021, "G80", "Sedan", "S58 twin-turbo, available manual"),
    ("BMW", "M4", 2021, "G82", "Coupe", "S58 big-grille coupe"),
    ("BMW", "M5", 2013, "F10", "Sedan", "S63 twin-turbo V8 super-sedan"),
    ("BMW", "M5", 2021, "F90", "Sedan", "S63 xDrive 600hp super-sedan"),
    ("BMW", "i8", 2015, "I12", "Coupe", "Plug-in hybrid triple halo car"),
    ("BMW", "Z4", 2020, "M40i (G29)", "Roadster", "B58 Supra-twin roadster"),
    ("BMW", "540i", 2000, "E39", "Sedan", "M62 V8 enthusiast's 5-series"),
    ("BMW", "328i", 1998, "E36", "Coupe", "M52 affordable RWD tuner base"),
    ("BMW", "X3 M", 2021, "F97", "SUV", "S58 twin-turbo compact super-SUV"),
    ("BMW", "M1", 1980, "E26", "Coupe", "Giugiaro mid-engine supercar"),
    ("Audi", "S4", 2013, "B8", "Sedan", "3.0T supercharged quattro sedan"),
    ("Audi", "RS4", 2013, "B8", "Sedan", "4.2 FSI V8 quattro super-sedan"),
    ("Audi", "S6", 2016, "C7", "Sedan", "4.0T V8 quattro Q-ship"),
    ("Audi", "Sport Quattro", 1985, "S1", "Coupe", "Group B rally monster"),
    ("Audi", "R8", 2020, "V10 (Type 4S)", "Coupe", "Second-gen 5.2 V10 everyday supercar"),
    ("Mercedes-Benz", "C63 AMG", 2016, "W205", "Sedan", "Twin-turbo 4.0 V8 super-sedan"),
    ("Mercedes-Benz", "E55 AMG", 2004, "W211", "Sedan", "Supercharged M113K V8 Q-ship"),
    ("Mercedes-Benz", "CLK63 AMG", 2008, "Black Series (C209)", "Coupe", "6.2 V8 track-focused Black Series"),
    ("Mercedes-Benz", "300SL", 1955, "W198 Gullwing", "Coupe", "Fuel-injected gullwing legend"),
    ("Mercedes-Benz", "SLR McLaren", 2005, "C199", "Coupe", "Supercharged V8 Merc-McLaren GT"),
    ("Volkswagen", "Scirocco", 2010, "R (Mk3)", "Hatch", "EA888 turbo Euro-only hot coupe"),
    ("Volkswagen", "Golf R32", 2008, "Mk5", "Hatch", "VR6 DSG AWD cult hatch"),
    ("Volkswagen", "GTI", 2003, "Mk4 1.8T", "Hatch", "Tunable early-2000s GTI"),
    ("Volkswagen", "Golf GTI", 1983, "Mk1", "Hatch", "The original hot hatch"),
    ("Porsche", "918 Spyder", 2015, "918", "Coupe", "V8 plug-in hybrid hypercar"),
    ("Porsche", "959", 1987, "959", "Coupe", "Twin-turbo AWD tech tour de force"),
    ("Porsche", "914", 1973, "914/6", "Coupe", "Mid-engine VW-Porsche classic"),
    ("Porsche", "924", 1980, "924 Turbo", "Coupe", "Entry transaxle Porsche"),
    ("Porsche", "Panamera", 2014, "Turbo (970)", "Sedan", "V8 four-door grand tourer"),
    ("Porsche", "Cayenne", 2022, "Turbo GT (9YA)", "SUV", "Twin-turbo V8 super-SUV"),
    ("Porsche", "911 GT3", 2022, "992", "Coupe", "4.0 flat-six, available manual"),
    ("Porsche", "356", 1957, "Speedster", "Roadster", "Air-cooled roadster origin"),

    # British
    ("McLaren", "P1", 2014, "P1", "Coupe", "V8 plug-in hybrid holy-trinity hypercar"),
    ("McLaren", "570S", 2016, "Sports Series", "Coupe", "Entry twin-turbo V8 McLaren"),
    ("Aston Martin", "DB5", 1964, "DB5", "Coupe", "The James Bond grand tourer"),
    ("Aston Martin", "Vanquish", 2003, "V12", "Coupe", "V12 GT flagship, paddle-shift"),
    ("Jaguar", "XJ220", 1993, "XJ220", "Coupe", "Twin-turbo V6 90s hypercar"),
    ("Jaguar", "XKR-S", 2012, "X150", "Coupe", "Supercharged V8 British bruiser"),
    ("Lotus", "Esprit", 1999, "V8", "Coupe", "Turbo V8 wedge, Bond submarine car"),
    ("Caterham", "Seven", 2015, "620R", "Roadster", "Featherweight supercharged track toy"),
    ("TVR", "Sagaris", 2005, "Sagaris", "Coupe", "Raw straight-six British hot rod"),
    ("MG", "MGB", 1970, "Chrome bumper", "Roadster", "Affordable British roadster staple"),
    ("Triumph", "TR6", 1972, "TR6", "Roadster", "Straight-six British roadster"),
    ("Austin-Healey", "3000", 1965, "Mk III", "Roadster", "Big Healey rally roadster"),
    ("Bentley", "Continental GT", 2010, "W12", "Coupe", "W12 grand-touring bruiser"),

    # Italian exotics
    ("Ferrari", "308 GTB", 1980, "Type F106", "Coupe", "Magnum's V8 Ferrari"),
    ("Ferrari", "F50", 1996, "F50", "Coupe", "V12 open-top 90s hypercar"),
    ("Ferrari", "LaFerrari", 2015, "F150", "Coupe", "V12 hybrid holy-trinity flagship"),
    ("Ferrari", "550 Maranello", 1998, "Type F133", "Coupe", "Front-V12 gated-manual GT"),
    ("Ferrari", "812 Superfast", 2018, "Type F152M", "Coupe", "6.5 NA V12 front-engine flagship"),
    ("Ferrari", "250 GT", 1962, "SWB", "Coupe", "Front-V12 classic-era icon"),
    ("Lamborghini", "Miura", 1969, "P400", "Coupe", "The first mid-engine supercar"),
    ("Lamborghini", "Urus", 2019, "Urus", "SUV", "Twin-turbo V8 super-SUV"),
    ("Maserati", "Bora", 1973, "Tipo 117", "Coupe", "Giugiaro V8 mid-engine classic"),
    ("Maserati", "Quattroporte", 2008, "V (M139)", "Sedan", "Ferrari-V8 four-door GT"),
    ("Lancia", "Stratos", 1975, "Stratos HF", "Coupe", "Ferrari-V6 rally weapon"),
    ("Alfa Romeo", "8C Competizione", 2008, "8C", "Coupe", "Maserati-V8 carbon GT"),
    ("Alfa Romeo", "GTV6", 1983, "Tipo 116", "Coupe", "Busso V6 transaxle coupe"),
    ("Alfa Romeo", "Stelvio", 2018, "Quadrifoglio", "SUV", "Ferrari-derived twin-turbo super-SUV"),
    ("Pagani", "Zonda", 2005, "C12 F", "Coupe", "AMG-V12 art-object hypercar"),
    ("De Tomaso", "Pantera", 1972, "GTS", "Coupe", "Ford-V8 Italian-American exotic"),

    # American — modern performance, muscle, off-road, EV
    ("Ford", "Mustang", 2024, "Dark Horse (S650)", "Coupe", "Track-honed Coyote, latest Mustang"),
    ("Ford", "GT", 2017, "2nd Gen", "Coupe", "Twin-turbo EcoBoost V6 Le Mans racer"),
    ("Ford", "Sierra", 1987, "RS500 Cosworth", "Sedan", "Turbo Group A touring-car legend"),
    ("Ford", "Escort", 1994, "RS Cosworth", "Hatch", "Turbo AWD rally homologation"),
    ("Ford", "F-150", 1999, "SVT Lightning", "Truck", "Supercharged sport-truck OG"),
    ("Ford", "Bronco", 2021, "6th Gen (U725)", "SUV", "Retro turbo off-roader revival"),
    ("Ford", "Ranger", 2024, "Raptor", "Truck", "Twin-turbo V6 midsize desert truck"),
    ("Shelby", "GT500", 1967, "Mk I", "Coupe", "Big-block Shelby Mustang classic"),
    ("Chevrolet", "Impala", 1996, "SS (LT1)", "Sedan", "LT1 full-size sleeper sedan"),
    ("Chevrolet", "Nova", 1970, "SS 396", "Coupe", "Small-body big-block muscle"),
    ("Chevrolet", "Corvette", 1962, "C1", "Roadster", "The original American sports car"),
    ("Chevrolet", "El Camino", 1970, "SS 454", "Truck", "Muscle-era car-truck"),
    ("Chevrolet", "Camaro", 1970, "SS 396 (2nd Gen)", "Coupe", "Second-gen big-block muscle"),
    ("Chevrolet", "Tahoe", 2021, "RST (5th Gen)", "SUV", "Full-size family SUV workhorse"),
    ("Chevrolet", "Bolt", 2022, "EUV", "Hatch", "Affordable everyday EV"),
    ("Dodge", "Challenger", 2018, "SRT Demon", "Coupe", "Drag-strip supercharged Hemi"),
    ("Dodge", "Stealth", 1992, "R/T Turbo", "Coupe", "3000GT-twin AWD turbo"),
    ("Dodge", "Charger", 1969, "Daytona", "Coupe", "Winged NASCAR homologation"),
    ("Dodge", "Viper", 1996, "GTS (Gen 2)", "Coupe", "8.0 V10 'double bubble' coupe"),
    ("Plymouth", "Duster", 1970, "340", "Coupe", "Budget small-block muscle"),
    ("Cadillac", "Escalade", 2023, "V (5th Gen)", "SUV", "Supercharged 682hp super-SUV"),
    ("Cadillac", "XLR", 2006, "V", "Roadster", "Supercharged Northstar roadster"),
    ("Pontiac", "G8", 2009, "GXP", "Sedan", "LS3 Holden-based super-sedan"),
    ("Buick", "GSX", 1970, "Stage 1", "Coupe", "455 big-block A-body muscle"),
    ("Chrysler", "Crossfire", 2005, "SRT-6", "Coupe", "Supercharged Mercedes-based coupe"),
    ("Saturn", "Sky", 2008, "Redline", "Roadster", "Turbo Kappa roadster (Solstice twin)"),
    ("GMC", "Hummer EV", 2022, "Pickup", "Truck", "1000hp electric off-road behemoth"),
    ("GMC", "Canyon", 2023, "AT4X (3rd Gen)", "Truck", "Off-road turbo midsize truck"),
    ("Hummer", "H1", 2006, "Alpha", "SUV", "Military-derived off-road behemoth"),
    ("Jeep", "Gladiator", 2021, "JT Mojave", "Truck", "Wrangler-based midsize desert truck"),
    ("Jeep", "Grand Wagoneer", 2022, "WS", "SUV", "Full-size luxury three-row Jeep"),

    # Korean
    ("Hyundai", "Tiburon", 2007, "GK", "Coupe", "Affordable V6 sport coupe"),
    ("Kia", "K5", 2021, "GT", "Sedan", "Turbo-four sport sedan value pick"),
    ("Kia", "Forte", 2020, "GT", "Sedan", "Turbo compact sport sedan"),
    ("Genesis", "G90", 2023, "2nd Gen", "Sedan", "Twin-turbo V6 flagship luxury sedan"),
    ("Genesis", "GV80", 2021, "JX1", "SUV", "Twin-turbo luxury three-row SUV"),

    # EV / modern performance
    ("Tesla", "Model Y", 2021, "Performance", "SUV", "Dual-motor performance crossover"),
    ("Tesla", "Roadster", 2010, "Gen 1", "Roadster", "Lotus-based EV that started it all"),
    ("Tesla", "Cybertruck", 2024, "Cyberbeast", "Truck", "Stainless tri-motor electric truck"),
    ("Rivian", "R1S", 2022, "Launch Edition", "SUV", "Quad-motor electric adventure SUV"),
    ("BMW", "i4", 2022, "M50 (G26)", "Sedan", "Dual-motor electric gran coupe"),
    ("Polestar", "2", 2023, "BST edition", "Sedan", "Volvo-based performance EV fastback"),

    # Land Rover / Euro luxury SUV
    ("Land Rover", "Defender", 2020, "L663", "SUV", "Reborn luxury off-road icon"),
    ("Land Rover", "Range Rover", 2022, "L460", "SUV", "Twin-turbo V8 luxury flagship SUV"),

    # Euro hot hatches / classics
    ("Mini", "Cooper", 1967, "Classic Cooper S", "Hatch", "The original giant-killer"),
    ("Fiat", "X1/9", 1979, "Bertone", "Coupe", "Mid-engine budget wedge"),
    ("Renault", "5", 1982, "Turbo", "Hatch", "Mid-engine Group B pocket rocket"),
    ("Renault", "Clio", 2005, "RS 182", "Hatch", "Naturally aspirated corner-carver"),
    ("Peugeot", "306", 1998, "GTI-6", "Hatch", "Sweet-handling 90s hot hatch"),
    ("Volvo", "C30", 2010, "T5 (P1)", "Hatch", "Turbo five-cylinder shooting-brake hatch"),
    ("Volvo", "240", 1985, "Turbo", "Sedan", "Brick turbo Group A homologation"),
    ("Saab", "900", 1988, "Turbo (Classic)", "Hatch", "Quirky turbo Swede cult classic"),
    ("Opel", "Manta", 1978, "GT/E", "Coupe", "German rear-drive rally coupe"),
    ("Skoda", "Octavia", 2016, "vRS (Mk3)", "Hatch", "EA888 turbo VW-family sleeper"),
    ("SEAT", "Leon", 2010, "Cupra R (Mk2)", "Hatch", "Spanish Golf-based hot hatch"),
    ("Abarth", "595", 2018, "Competizione", "Hatch", "Scorpion-badged turbo pocket rocket"),

    # --- Orphan-closers (2026-07): catalog homes for curated files that had none.
    #     Q50 trims split like the Camaro/Mustang bindings (trim-gated); the S3
    #     entry is the 8Y because the curated file's 306hp is the US 8Y figure
    #     (US 8V made 288-292hp — verified 2026-07, so the 8V entry stays unbound).
    ("Infiniti", "Q50", 2015, "3.7 (V37)", "Sedan", "VQ37VHR 328hp launch trim"),
    ("Infiniti", "Q50", 2019, "3.0t (V37)", "Sedan", "VR30DDTT twin-turbo daily sport sedan"),
    ("Infiniti", "Q50", 2019, "Red Sport 400 (V37)", "Sedan", "400hp twin-turbo flagship trim"),
    ("Audi", "S3", 2023, "8Y", "Sedan", "306hp EA888 quattro compact sport sedan"),

    # --- Catalog batch 5 (2026-07): everyday economy & family cars for
    #     NON-enthusiasts — the commuters, crossovers, and minivans regular
    #     buyers actually research. The profile engine (recalls/complaints/
    #     reliability) is most valuable exactly here. ---
    # Toyota
    ("Toyota", "Camry", 2009, "XV40", "Sedan", "Bulletproof used-commuter benchmark"),
    ("Toyota", "Camry", 2015, "XV50", "Sedan", "Roomy, dependable midsize staple"),
    ("Toyota", "Corolla", 2010, "E140", "Sedan", "Set-and-forget commuter appliance"),
    ("Toyota", "Corolla", 2016, "E170", "Sedan", "Safe-pick compact with standard safety tech"),
    ("Toyota", "Prius", 2012, "XW30 (3rd Gen)", "Hatch", "50mpg hybrid commuting workhorse"),
    ("Toyota", "C-HR", 2019, "AX10", "SUV", "Style-first subcompact crossover"),
    ("Toyota", "Venza", 2021, "XU80", "SUV", "Hybrid-only midsize two-row crossover"),
    ("Toyota", "RAV4", 2015, "XA40", "SUV", "Used-market compact-SUV staple"),
    ("Toyota", "Highlander", 2015, "XU50", "SUV", "Three-row family default, V6"),
    ("Toyota", "Sienna", 2015, "3rd Gen (XL30)", "Minivan", "V6 family hauler, AWD available"),
    ("Toyota", "Matrix", 2009, "2nd Gen", "Hatch", "Corolla-based practical hatch"),
    # Honda
    ("Honda", "Civic", 2003, "7th Gen (EM2)", "Sedan", "Simple, durable commuter Civic"),
    ("Honda", "CR-V", 2007, "3rd Gen (RE)", "SUV", "Used-market family-hauler favorite"),
    ("Honda", "CR-V", 2023, "6th Gen (RS)", "SUV", "Latest hybrid-available compact SUV"),
    ("Honda", "Odyssey", 2012, "4th Gen (RL5)", "Minivan", "Spacious V6 family minivan"),
    ("Honda", "Pilot", 2023, "4th Gen", "SUV", "Latest three-row family SUV"),
    ("Honda", "Passport", 2019, "3rd Gen", "SUV", "Two-row Pilot for weekend duty"),
    # Nissan
    ("Nissan", "Altima", 2010, "L32", "Sedan", "Ubiquitous used midsize commuter"),
    ("Nissan", "Altima", 2019, "L34", "Sedan", "Midsize commuter, AWD available"),
    ("Nissan", "Sentra", 2020, "B18", "Sedan", "Much-improved budget compact"),
    ("Nissan", "Versa", 2020, "N18", "Sedan", "One of the cheapest new cars, grown up"),
    ("Nissan", "Murano", 2015, "Z52", "SUV", "Plush V6 midsize crossover"),
    ("Nissan", "Pathfinder", 2022, "R53", "SUV", "Back-to-rugged three-row family SUV"),
    ("Nissan", "Kicks", 2018, "P15", "SUV", "Budget city crossover"),
    # Hyundai
    ("Hyundai", "Elantra", 2013, "5th Gen (MD)", "Sedan", "Value compact of the early 2010s"),
    ("Hyundai", "Elantra", 2021, "7th Gen (CN7)", "Sedan", "Sharp-suited value compact, hybrid available"),
    ("Hyundai", "Sonata", 2011, "6th Gen (YF)", "Sedan", "Fluidic-design midsize value pick"),
    ("Hyundai", "Sonata", 2020, "8th Gen (DN8)", "Sedan", "Feature-dense midsize sedan"),
    ("Hyundai", "Tucson", 2022, "4th Gen (NX4)", "SUV", "Bold compact family crossover"),
    ("Hyundai", "Santa Fe", 2019, "4th Gen (TM)", "SUV", "Comfort-first midsize SUV"),
    ("Hyundai", "Kona", 2018, "1st Gen (OS)", "SUV", "Zippy subcompact crossover"),
    ("Hyundai", "Accent", 2018, "5th Gen (HC)", "Sedan", "Basic, honest budget sedan"),
    ("Hyundai", "Palisade", 2020, "1st Gen (LX2)", "SUV", "Value three-row family flagship"),
    ("Hyundai", "Venue", 2021, "1st Gen (QX)", "SUV", "Tiny entry crossover"),
    ("Hyundai", "Ioniq 5", 2022, "1st Gen (NE)", "SUV", "Retro-futurist everyday EV"),
    # Kia
    ("Kia", "Soul", 2020, "3rd Gen (SK3)", "Hatch", "Boxy practical urban runabout"),
    ("Kia", "Sportage", 2023, "5th Gen (NQ5)", "SUV", "Compact family crossover, hybrid available"),
    ("Kia", "Sorento", 2021, "4th Gen (MQ4)", "SUV", "Right-size three-row SUV"),
    ("Kia", "Optima", 2016, "4th Gen (JF)", "Sedan", "Value midsize commuter sedan"),
    ("Kia", "Rio", 2018, "4th Gen (YB)", "Sedan", "Cheap, cheerful basic transport"),
    ("Kia", "Niro", 2018, "1st Gen (DE)", "SUV", "Hybrid crossover mpg champion"),
    ("Kia", "Seltos", 2021, "1st Gen (SP2)", "SUV", "Boxy subcompact with real space"),
    ("Kia", "Carnival", 2022, "4th Gen (KA4)", "Minivan", "SUV-styled family minivan"),
    # Subaru
    ("Subaru", "Forester", 2019, "5th Gen (SK)", "SUV", "Visibility-and-AWD family favorite"),
    ("Subaru", "Legacy", 2020, "7th Gen (BW)", "Sedan", "AWD-standard midsize sedan"),
    ("Subaru", "Impreza", 2017, "5th Gen (GK)", "Hatch", "Practical AWD compact"),
    # Mazda
    ("Mazda", "CX-9", 2016, "2nd Gen (TC)", "SUV", "Three-row with an upscale cabin"),
    # Volkswagen
    ("Volkswagen", "Jetta", 2019, "A7", "Sedan", "Roomy budget German commuter"),
    ("Volkswagen", "Passat", 2016, "NMS (US)", "Sedan", "Roomy US-built midsize"),
    ("Volkswagen", "Tiguan", 2019, "2nd Gen (AD1)", "SUV", "Compact crossover, third row available"),
    ("Volkswagen", "Taos", 2022, "1st Gen", "SUV", "Entry subcompact crossover"),
    ("Volkswagen", "Atlas", 2018, "1st Gen (CA)", "SUV", "US-sized three-row family SUV"),
    ("Volkswagen", "Golf", 2015, "Mk7 TSI", "Hatch", "Refined do-everything hatch"),
    ("Volkswagen", "Beetle", 2013, "A5", "Coupe", "Retro-modern Beetle revival"),
    # Ford
    ("Ford", "Escape", 2020, "4th Gen", "SUV", "Car-like compact crossover, hybrid available"),
    ("Ford", "Explorer", 2020, "6th Gen (U625)", "SUV", "RWD-based three-row family SUV"),
    ("Ford", "Edge", 2016, "2nd Gen", "SUV", "Comfortable two-row midsize crossover"),
    ("Ford", "Fusion", 2014, "2nd Gen (CD4)", "Sedan", "Handsome midsize, hybrid available"),
    ("Ford", "Focus", 2012, "3rd Gen (C346)", "Hatch", "Global-platform compact commuter"),
    ("Ford", "Fiesta", 2014, "6th Gen", "Hatch", "Subcompact city car"),
    # Chevrolet
    ("Chevrolet", "Malibu", 2016, "9th Gen (E2XX)", "Sedan", "Midsize commuter sedan"),
    ("Chevrolet", "Cruze", 2016, "2nd Gen (D2XX)", "Sedan", "Compact commuter, diesel available"),
    ("Chevrolet", "Equinox", 2018, "3rd Gen", "SUV", "Compact family crossover staple"),
    ("Chevrolet", "Traverse", 2018, "2nd Gen (C1XX)", "SUV", "Minivan-space three-row crossover"),
    ("Chevrolet", "Trax", 2024, "2nd Gen", "SUV", "Budget crossover value glow-up"),
    ("Chevrolet", "Spark", 2016, "2nd Gen (M400)", "Hatch", "Tiny city-car cheapest-new pick"),
    ("Chevrolet", "Volt", 2017, "2nd Gen", "Hatch", "Plug-in hybrid commuting pioneer"),
    ("Chevrolet", "Impala", 2014, "10th Gen", "Sedan", "Full-size comfort sedan"),
    # Buick / GMC
    ("Buick", "Encore", 2015, "1st Gen", "SUV", "Quiet subcompact luxury-lite crossover"),
    ("Buick", "Enclave", 2018, "2nd Gen", "SUV", "Plush three-row family crossover"),
    ("GMC", "Terrain", 2018, "2nd Gen", "SUV", "Equinox's squared-off twin"),
    ("GMC", "Acadia", 2017, "2nd Gen", "SUV", "Right-sized three-row crossover"),
    # Chrysler / Dodge / Jeep
    ("Chrysler", "Pacifica", 2017, "RU", "Minivan", "Family minivan, plug-in hybrid available"),
    ("Dodge", "Grand Caravan", 2012, "5th Gen (RT)", "Minivan", "Budget family-hauler workhorse"),
    ("Dodge", "Journey", 2012, "JC", "SUV", "Budget three-row crossover"),
    ("Jeep", "Cherokee", 2014, "KL", "SUV", "Compact crossover with trail cred"),
    ("Jeep", "Grand Cherokee", 2012, "WK2", "SUV", "V6 do-it-all family SUV"),
    ("Jeep", "Compass", 2018, "2nd Gen (MP)", "SUV", "Entry Jeep-badged crossover"),
    ("Jeep", "Renegade", 2015, "BU", "SUV", "Boxy Fiat-based small Jeep"),
    # Mitsubishi
    ("Mitsubishi", "Mirage", 2015, "6th Gen (A03)", "Hatch", "Bare-bones cheapest-new-car pick"),
    ("Mitsubishi", "Outlander Sport", 2013, "GA", "SUV", "Budget subcompact crossover"),
]


def main():
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = os.path.join(here, "data", "catalog.json")
    catalog = [
        {"make": mk, "model": md, "year": yr, "generation": gen, "body": body, "note": note}
        for (mk, md, yr, gen, body, note) in CARS
    ]
    with open(out, "w", encoding="utf-8") as f:
        json.dump(catalog, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(f"Wrote {len(catalog)} cars to {out}")


if __name__ == "__main__":
    main()
